### ISSUE TITLE
Add a switch/feature to explicitly ignore system internet proxy (configured in IE)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1062]
This is similar to what was added to the puppet provider for Chocolatey - https://github.com/chocolatey/puppet-chocolatey/pull/144, and later with the install.ps1 from Chocolatey.org (https://github.com/chocolatey/chocolatey.org/issues/433), except at the Chocolatey client level itself.

**Comment by Cubix651** [comment]
I've just started competing with this issue :)

**Comment by ferventcoder** [comment]
Competing? Does this mean working on?

**Comment by Cubix651** [comment]
Yep. Can I?

**Comment by ferventcoder** [comment]
Sure thing. Long as you are able to sign the CLA and meet all of the requirements noted in the CONTRIBUTING document.

**Comment by mwallner** [comment]
will this issue affect the `choco download` command as well ?

**Comment by ferventcoder** [comment]
It might! 👍

**Comment by Cubix651** [comment]
I'm investigating how proxy is set and used. I've found that, for instance, choco list uses Search method from AggregateRepository from nuget package. So for correctly working proxy in nuget, environmental variables `http_proxy` and `https_proxy` are set. Am I correct?

If so, it will demand to change nuget to achieve proxy ignoring functionality. Because now nugets isn't offering such one, is it? I've tried to use `no_proxy` set to `*` and `http(s)_proxy` to `a:b@localhost` but I didn't work.

Any suggestions?

**Comment by mwallner** [comment]
I thought there is a fork of nuget for choco where such changes can be made? (https://github.com/chocolatey/nuget-chocolatey)

**Comment by Cubix651** [comment]
I'm still working on solution. I've wrote fix for nuget-chocolatey (as suggested @mwallner). Could you explain me how the nuget-chocolatey is deployed into choco? I've tried to replace old Nuget.Core.dll with new version (just for local check) but I get runtime errors: 
`System.IO.FileLoadException was unhandled by user code
  FileName=NuGet.Core, Version=2.11.0.0, Culture=neutral, PublicKeyToken=null
  FusionLog=""
  HResult=-2146234300
  Message=Could not load file or assembly 'NuGet.Core, Version=2.11.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
  Source=chocolatey
  StackTrace:
       at chocolatey.infrastructure.app.registration.ContainerBinding.RegisterComponents(Container container)
       at chocolatey.infrastructure.registration.SimpleInjectorContainer.initialize() in C:\Users\cubix651\Desktop\choco\src\chocolatey\infrastructure\registration\SimpleInjectorContainer.cs:line 61
       at System.Lazy`1.CreateValue()
  InnerException: 
`
