### ISSUE TITLE
Install.ps1 shows the following when run via puppet

### ISSUE THREAD

**Issue by riponbanik** [chocolatey/choco#1063]
Error: Could not update: Execution of 'C:\ProgramData\chocolatey\bin\choco.exe install {} -y ' returned 1: Chocolatey v0
.10.3
Installing the following packages:
log4net:WARN Exception while rendering format [{}]
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at log4net.Util.SystemStringFormat.StringFormat(IFormatProvider provider, String format, Object[] args)
<log4net.Error>Exception during StringFormat: Input string was not in a correct format. <format>{}</format><args>{}</arg
s></log4net.Error>
log4net:WARN Exception while rendering format [{}]
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at log4net.Util.SystemStringFormat.StringFormat(IFormatProvider provider, String format, Object[] args)
log4net:WARN Exception while rendering format [{}]
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at log4net.Util.SystemStringFormat.StringFormat(IFormatProvider provider, String format, Object[] args)
By installing you accept licenses for the packages.
log4net:WARN Exception while rendering format [{} not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but t
he version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"]
System.FormatException: Input string was not in a correct format.

**Comment by ferventcoder** [comment]
@riponbanik what is in your manifest?

**Comment by ferventcoder** [comment]
I am going to preemptively put invalid on this as I think you may be doing something incorrect.

~~~puppet
package { 'nameofpkg':
  ensure   => installed,
  provider => chocolatey,
}
~~~

* https://forge.puppet.com/puppetlabs/chocolatey#packages
* https://forge.puppet.com/puppetlabs/chocolatey#package-provider-chocolatey

**Comment by ferventcoder** [comment]
Your package file cannot have `{` or `}` as part of the name, that is why this is invalid. I'm would like to help you with getting your manifest correct though.

**Comment by riponbanik** [comment]
I have resolved the issue by checking the list of packages not empty. Thanks @ferventcoder for looking into this.

**Comment by ferventcoder** [comment]
I would think that the Choco Puppet provider could do something here for validation.  It may not be bad to follow up with an issue at https://tickets.puppet.com/browse/MODULES and ask that the provider could validate the input for the package name.  Thanks!
