### ISSUE TITLE
proxyBypassList not bypassing proxy

### ISSUE THREAD

**Issue by vihoti** [chocolatey/choco#1694]
Hello,

I have the following problem.
I want to push a package to an internal Artifactory repository.
I have set up the proxy settings in the chocolatey.config file like this:
`<add key="proxy" value="http://user:pwd@www.proxy.int:8080" description="Explicit proxy location. Available in 0.9.9.9+." />
<add key="proxyUser" value="" description="Optional proxy user. Available in 0.9.9.9+." />
<add key="proxyPassword" value="" description="Optional proxy password. Encrypted. Available in 0.9.9.9+." />
<add key="webRequestTimeoutSeconds" value="30" description="Default timeout for web requests. Available in 0.9.10+." />
<add key="proxyBypassList" value="127.0.0.1,*.internal.int,10.1.*" description="Optional proxy bypass list. Comma separated. Available in 0.10.4+." />
<add key="proxyBypassOnLocal" value="true" description="Bypass proxy for local connections. Available in 0.10.4+." />
`

When I try to push the package with:
`choco push ./package.nupkg --source https://artifactoryserver.internal.int/artifactory/testrepo/ -k "usr:pwd"`
the push fails with the following error:
[chocoerror.txt](https://github.com/chocolatey/choco/files/2686953/chocoerror.txt)

If I however remove the proxy (i.e. http://user:pwd@www.proxy.int), but still leave the proxyBypassList, the push succeeds.
[chocosuccess.txt](https://github.com/chocolatey/choco/files/2686959/chocosuccess.txt)

I also tried it with:

choco config set proxy http://www.proxy.int:8080
choco config set proxyUser usr
choco config set proxyPassword pwd
choco config set proxyBypassList "127.0.0.1,\*.internal.int,10.1.\*"
choco config set proxyBypassOnLocal true

But then I get the following exception:
`Chocolatey had an error occur:
System.NotSupportedException: The ServicePointManager does not support proxies with the usr scheme.
   at System.Net.ServicePointManager.FindServicePointHelper(Uri address, Boolean isProxyServicePoint)
   at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)
...
`

Is the proxyBypassList not supposed to bypass the proxy if the domain of the source to where the package is being pushed to is specified in the bypass list?
According to the above behaviour chocolatey still seems to try and authenticate to the proxy even though the bypass list is specified.

**Comment by vihoti** [comment]
I forgot to mention, I am using:

- Windows 10 Enterprise

- Chocolatey version 0.10.11

I get my system proxy settings from a script address.

**Comment by boernsen-development** [comment]
As far as I remember the [proxyBypassList](https://docs.chocolatey.org/en-us/guides/usage/proxy-settings-for-chocolatey/#explicit-proxy-settings) uses regex syntax while you are using wildcard syntax. This was quiet confusing to me when I first figured out. This also means that dots `.` must be escaped like `\.` to be interpreted just as dot. Could this be a cause for the issues described?

**Comment by vihoti** [comment]
Thank you for your response.
As this issue is not relevant for me anymore, I will close it.
