### ISSUE TITLE
cannot connect to feed after updating to > 0.10.11

### ISSUE THREAD

**Issue by f0rdprefect** [chocolatey/choco#1835]
### What You Are Seeing?

After updating / or installing choco to version > 0.10.11 (12 or 13 that is) I can no longer use package feeds hosted on simple server instances. I have set up two instances of 

https://hub.docker.com/r/sunside/simple-nuget-server/

which work fine with previous versions of chocolatey. Confirmed that behavior by down and upgrading a couple of times. 

### What is Expected?

choco still working / older version telling me that the feed will break soon

### How Did You Get This To Happen? (Steps to Reproduce)

see log below. First I will include output of 0.10.13 then 0.10.11 is shown.

### Output Log

0.10.13
----------
2019-05-28 14:52:32,627 6016 [DEBUG] - XmlConfiguration is now operational
2019-05-28 14:52:32,694 6016 [INFO ] - ============================================================
2019-05-28 14:52:33,366 6016 [INFO ] - Chocolatey v0.10.13
2019-05-28 14:52:33,381 6016 [DEBUG] - Chocolatey is running on Windows v 10.0.17134.0
2019-05-28 14:52:33,386 6016 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2019-05-28 14:52:33,394 6016 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2019-05-28 14:52:33,413 6016 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade 19.03 --force -v -d
2019-05-28 14:52:33,417 6016 [DEBUG] - Received arguments: upgrade 19.03 --force -v -d
2019-05-28 14:52:33,483 6016 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2019-05-28 14:52:33,499 6016 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2019-05-28 14:52:33,510 6016 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2019-05-28 14:52:34,949 6016 [DEBUG] - Performing validation checks.
2019-05-28 14:52:34,965 6016 [DEBUG] - Global Configuration Validation Checks:
2019-05-28 14:52:34,970 6016 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2019-05-28 14:52:34,973 6016 [DEBUG] - System State Validation Checks:
2019-05-28 14:52:34,980 6016 [DEBUG] -  Reboot Requirement Checks:
2019-05-28 14:52:34,985 6016 [DEBUG] -  - Pending Computer Rename = Checked
2019-05-28 14:52:34,989 6016 [DEBUG] -  - Pending Component Based Servicing = Checked
2019-05-28 14:52:34,996 6016 [DEBUG] -  - Pending Windows Auto Update = Checked
2019-05-28 14:52:35,000 6016 [DEBUG] -  - Pending File Rename Operations = Flagged
2019-05-28 14:52:35,010 6016 [INFO ] - 2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).
2019-05-28 14:52:35,013 6016 [INFO ] - 
2019-05-28 14:52:35,017 6016 [WARN ] - Validation Warnings:
2019-05-28 14:52:35,022 6016 [WARN ] -  - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

2019-05-28 14:52:35,030 6016 [DEBUG] - The source 'http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2019-05-28 14:52:35,034 6016 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2019-05-28 14:52:35,052 6016 [DEBUG] - Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\Administrator\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/'|

SourceType='normal'|Debug='True'|Verbose='True'|Trace='False'|
Force='True'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='19.03'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='19.03'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17134.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.13.0'|
Information.ChocolateyProductVersion='0.10.13'|
Information.FullName='choco, Version=0.10.13.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='Administrator'|
Information.UserDomainName='spirit-sw-test'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='False'|Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='True'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2019-05-28 14:52:35,064 6016 [DEBUG] - _ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
2019-05-28 14:52:35,081 6016 [INFO ] - Upgrading the following packages:
2019-05-28 14:52:35,084 6016 [INFO ] - 19.03
2019-05-28 14:52:35,090 6016 [INFO ] - By upgrading you accept licenses for the packages.
2019-05-28 14:52:35,334 6016 [DEBUG] - Using 'http://chocolatey:5000/'.
2019-05-28 14:52:35,447 6016 [DEBUG] - - Supports prereleases? 'True'.
2019-05-28 14:52:35,451 6016 [DEBUG] - - Is ServiceBased? 'True'.
2019-05-28 14:52:35,638 6016 [WARN ] - 
Chocolatey upgraded 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-05-28 14:52:35,643 6016 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2019-05-28 14:52:35,663 6016 [ERROR] - Chocolatey had an error occur:
System.InvalidOperationException: Could not connect to the feed specified at 'http://chocolatey:5000/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity. ---> System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: InternalServerError
   at System.Data.Services.Client.QueryResult.Execute()
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at NuGet.DataServiceQueryWrapper`1.Execute[TResult](Func`1 action)
   --- End of inner exception stack trace ---
   at NuGet.DataServiceQueryWrapper`1.Execute[TResult](Func`1 action)
   at NuGet.DataServiceQueryWrapper`1.<GetAll>d__14.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at chocolatey.infrastructure.app.services.NugetService.find_package(String packageName, SemanticVersion version, ChocolateyConfiguration config, IPackageRepository repository)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Boolean performAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.upgrade_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2019-05-28 14:52:35,672 6016 [DEBUG] - Exiting with 1

0.10.11
----------
2019-05-28 14:48:52,770 876 [DEBUG] - XmlConfiguration is now operational
2019-05-28 14:48:52,823 876 [INFO ] - ============================================================
2019-05-28 14:48:53,518 876 [INFO ] - Chocolatey v0.10.11
2019-05-28 14:48:53,536 876 [DEBUG] - Chocolatey is running on Windows v 10.0.17134.0
2019-05-28 14:48:53,542 876 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2019-05-28 14:48:53,546 876 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2019-05-28 14:48:53,565 876 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade 19.03 --force -v -d
2019-05-28 14:48:53,568 876 [DEBUG] - Received arguments: upgrade 19.03 --force -v -d
2019-05-28 14:48:53,654 876 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2019-05-28 14:48:53,668 876 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2019-05-28 14:48:53,682 876 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2019-05-28 14:48:55,076 876 [DEBUG] - The source 'http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2019-05-28 14:48:55,079 876 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple 
 check to be sure no sensitive data is shown, especially if copying 
 output to a gist for review.
2019-05-28 14:48:55,105 876 [DEBUG] - Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\Administrator\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/'|

SourceType='normal'|Debug='True'|Verbose='True'|Trace='False'|
Force='True'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='19.03'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='19.03'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17134.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.11.0'|
Information.ChocolateyProductVersion='0.10.11'|
Information.FullName='choco, Version=0.10.11.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='Administrator'|
Information.UserDomainName='spirit-sw-test'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='False'|Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='True'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
PinCommand.Command='unknown'|OutdatedCommand.IgnorePinned='False'|
Proxy.BypassOnLocal='True'|
2019-05-28 14:48:55,113 876 [DEBUG] - _ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
2019-05-28 14:48:55,126 876 [INFO ] - Upgrading the following packages:
2019-05-28 14:48:55,130 876 [INFO ] - 19.03
2019-05-28 14:48:55,137 876 [INFO ] - By upgrading you accept licenses for the packages.
2019-05-28 14:48:55,917 876 [INFO ] - 19.03 v19.03.0.450 is the latest version available based on your source(s).
2019-05-28 14:48:56,035 876 [DEBUG] - Backing up existing 19.03 prior to operation.
2019-05-28 14:48:56,042 876 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\19.03'
 to 'C:\ProgramData\chocolatey\lib-bkp\19.03'

and so on...

**Comment by mkevenaar** [comment]
@f0rdprefect This is a known issue ( see #1770 ), Could you please try to use the latest beta?

**Comment by f0rdprefect** [comment]
short answer: does not help. Will post log tomorrow

**Comment by f0rdprefect** [comment]
@mkevenaar here comes the log:

2019-05-29 08:25:42,763 4356 [DEBUG] - XmlConfiguration is now operational
2019-05-29 08:25:42,818 4356 [INFO ] - ============================================================
2019-05-29 08:25:43,481 4356 [INFO ] - Chocolatey v0.10.14-beta-7-gb30427d
2019-05-29 08:25:43,500 4356 [DEBUG] - Chocolatey is running on Windows v 10.0.17134.0
2019-05-29 08:25:43,508 4356 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2019-05-29 08:25:43,514 4356 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2019-05-29 08:25:43,533 4356 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade 19.03 -v -d
2019-05-29 08:25:43,536 4356 [DEBUG] - Received arguments: upgrade 19.03 -v -d
2019-05-29 08:25:43,604 4356 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2019-05-29 08:25:43,617 4356 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2019-05-29 08:25:43,632 4356 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2019-05-29 08:25:45,249 4356 [DEBUG] - Performing validation checks.
2019-05-29 08:25:45,259 4356 [DEBUG] - Global Configuration Validation Checks:
2019-05-29 08:25:45,262 4356 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2019-05-29 08:25:45,273 4356 [DEBUG] - System State Validation Checks:
2019-05-29 08:25:45,277 4356 [DEBUG] -  Reboot Requirement Checks:
2019-05-29 08:25:45,293 4356 [DEBUG] -  - Pending Computer Rename = Checked
2019-05-29 08:25:45,303 4356 [DEBUG] -  - Pending Component Based Servicing = Checked
2019-05-29 08:25:45,307 4356 [DEBUG] -  - Pending Windows Auto Update = Checked
2019-05-29 08:25:45,310 4356 [DEBUG] -  - Pending File Rename Operations = Ignored
2019-05-29 08:25:45,312 4356 [DEBUG] -  - Pending Windows Package Installer = Checked
2019-05-29 08:25:45,325 4356 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2019-05-29 08:25:45,337 4356 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2019-05-29 08:25:45,340 4356 [DEBUG] - The source 'http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2019-05-29 08:25:45,345 4356 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2019-05-29 08:25:45,366 4356 [DEBUG] - Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\Administrator\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/'|

SourceType='normal'|Debug='True'|Verbose='True'|Trace='False'|
Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='19.03'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='19.03'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.17134.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.14.0'|
Information.ChocolateyProductVersion='0.10.14-beta-7-gb30427d'|
Information.FullName='choco, Version=0.10.14.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='Administrator'|
Information.UserDomainName='spirit-sw-test'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='False'|Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='True'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2019-05-29 08:25:45,373 4356 [DEBUG] - _ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
2019-05-29 08:25:45,386 4356 [INFO ] - Upgrading the following packages:
2019-05-29 08:25:45,389 4356 [INFO ] - 19.03
2019-05-29 08:25:45,391 4356 [INFO ] - By upgrading you accept licenses for the packages.
2019-05-29 08:25:45,648 4356 [DEBUG] - Using 'http://chocolatey:5000/'.
2019-05-29 08:25:45,759 4356 [DEBUG] - - Supports prereleases? 'True'.
2019-05-29 08:25:45,768 4356 [DEBUG] - - Is ServiceBased? 'True'.
2019-05-29 08:25:45,954 4356 [WARN ] - Error retrieving packages from source 'http://chocolatey:5000/':
 Could not connect to the feed specified at 'http://chocolatey:5000/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
2019-05-29 08:25:45,957 4356 [DEBUG] - Using 'https://update.raith.de/packages/'.
2019-05-29 08:25:46,013 4356 [DEBUG] - - Supports prereleases? 'True'.
2019-05-29 08:25:46,017 4356 [DEBUG] - - Is ServiceBased? 'True'.
2019-05-29 08:25:46,033 4356 [WARN ] - Error retrieving packages from source 'https://update.raith.de/packages/':
 Could not connect to the feed specified at 'https://update.raith.de/packages/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
2019-05-29 08:25:46,039 4356 [DEBUG] - Using 'https://chocolatey.org/api/v2/'.
2019-05-29 08:25:46,217 4356 [DEBUG] - - Supports prereleases? 'True'.
2019-05-29 08:25:46,231 4356 [DEBUG] - - Is ServiceBased? 'True'.
2019-05-29 08:25:46,326 4356 [WARN ] - 
19.03 was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""; Source(s): "http://chocolatey:5000/;https://update.raith.de/packages/;https://chocolatey.org/api/v2/"
2019-05-29 08:25:46,344 4356 [WARN ] - 
Chocolatey upgraded 0/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-05-29 08:25:46,346 4356 [INFO ] - 
2019-05-29 08:25:46,349 4356 [WARN ] - Warnings:
2019-05-29 08:25:46,351 4356 [WARN ] -  - 19.03 - 19.03 was not found with the source(s) listed.
2019-05-29 08:25:46,353 4356 [WARN ] - 
Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
2019-05-29 08:25:46,369 4356 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2019-05-29 08:25:46,383 4356 [DEBUG] - Exiting with 0

**Comment by f0rdprefect** [comment]
ok after reading the notes in the linked issue again I issued 

```
choco feature disable -n usePackageRepositoryOptimizations
```

Works ;)

**Comment by ferventcoder** [comment]
Duplicate of #1770
