### ISSUE TITLE
Could not create SSL/TLS secure channel error when installing Chocolatey.exe

### ISSUE THREAD

**Issue by israelvaldez** [chocolatey/choco#1995]
Starting today we've started to receive errors like the one below when getting the ps1 file that installs chocolatey from: https://chocolatey.org/install.ps1 where you guys expecting that to happen?
```
The request was aborted: Could not create SSL/TLS secure channel." ---> 
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
  at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
  at System.Net.WebClient.DownloadString(Uri address)
```

These can be fixed on our end by adding workarounds like the one below on Powershell, what is the official workaround that you'd recommend people to follow to alleviate this issue?
```
  $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
  [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
  [System.Net.ServicePointManager]::Expect100Continue = $true
```

**Comment by ferventcoder** [comment]
@israelvaldez I'm going to move this over to the chocolatey.org repo as this is where the issue is coming from, but I have questions.
