### ISSUE TITLE
choco uninstall foo gives error "package name is required"

### ISSUE THREAD

**Issue by altwohill** [chocolatey/choco#2040]
### What You Are Seeing?

```
PS C:\WINDOWS\system32> choco uninstall nodejs
Chocolatey v0.10.15
Package name is required. Please pass at least one package name to uninstall.
```

### What is Expected?

I provided the package name `nodejs` - I'd expect it to uninstall

### How Did You Get This To Happen? (Steps to Reproduce)
Open administrative powershell (or CMD)
run `choco uninstall nodejs`

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
2020-04-29 20:04:06,750 22024 [DEBUG] - Configuration: CommandName='list'|
CacheLocation='C:\Users\al\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='False'|Verbose='False'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|
RegularOutput='False'|
QuietOutput='False'|PromptForConfirmation='False'|
AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='-'|AllVersions='False'|
SkipPackageInstallProvider='False'|Prerelease='False'|ForceX86='False'|
OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19041.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='al'|Information.UserDomainName='GRIF'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\WINDOWS\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|ListCommand.LocalOnly='True'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='True'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2020-04-29 20:04:06,751 22024 [DEBUG] - _ Chocolatey:ChocolateyListCommand - Normal Run Mode _
2020-04-29 20:04:07,215 22024 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-04-29 20:04:07,218 22024 [DEBUG] - Exiting with 0
2020-04-29 20:04:28,191 44908 [DEBUG] - XmlConfiguration is now operational
2020-04-29 20:04:28,221 44908 [INFO ] - ============================================================
2020-04-29 20:04:28,333 44908 [INFO ] - Chocolatey v0.10.15
2020-04-29 20:04:28,340 44908 [DEBUG] - Chocolatey is running on Windows v 10.0.19041.0
2020-04-29 20:04:28,341 44908 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2020-04-29 20:04:28,342 44908 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2020-04-29 20:04:28,348 44908 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" uninstall nodejs
2020-04-29 20:04:28,349 44908 [DEBUG] - Received arguments: uninstall nodejs
2020-04-29 20:04:28,378 44908 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2020-04-29 20:04:28,383 44908 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2020-04-29 20:04:28,388 44908 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2020-04-29 20:04:28,426 44908 [DEBUG] - Performing validation checks.
2020-04-29 20:04:28,427 44908 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-04-29 20:04:28,431 44908 [ERROR] - Package name is required. Please pass at least one package name to uninstall.
2020-04-29 20:04:28,439 44908 [ERROR] - More Details: System.ApplicationException: Package name is required. Please pass at least one package name to uninstall.
   at chocolatey.infrastructure.app.commands.ChocolateyUninstallCommand.handle_validation(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<>c__DisplayClasse.<run>b__6()
   at chocolatey.infrastructure.app.configuration.ConfigurationOptions.parse_arguments_and_update_configuration(ICollection`1 args, ChocolateyConfiguration configuration, Action`1 setOptions, Action`1 afterParse, Action validateConfiguration, Action helpMessage)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<run>b__3(ICommand command)
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2020-04-29 20:04:28,440 44908 [DEBUG] - Exiting with 1
2020-04-29 20:06:23,586 38580 [DEBUG] - XmlConfiguration is now operational
2020-04-29 20:06:23,615 38580 [INFO ] - ============================================================
2020-04-29 20:06:23,729 38580 [INFO ] - Chocolatey v0.10.15
2020-04-29 20:06:23,736 38580 [DEBUG] - Chocolatey is running on Windows v 10.0.19041.0
2020-04-29 20:06:23,739 38580 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2020-04-29 20:06:23,740 38580 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2020-04-29 20:06:23,746 38580 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" uninstall nodejs --debug
2020-04-29 20:06:23,748 38580 [DEBUG] - Received arguments: uninstall nodejs --debug
2020-04-29 20:06:23,779 38580 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2020-04-29 20:06:23,784 38580 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2020-04-29 20:06:23,789 38580 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2020-04-29 20:06:23,826 38580 [DEBUG] - Performing validation checks.
2020-04-29 20:06:23,829 38580 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-04-29 20:06:23,838 38580 [ERROR] - Chocolatey had an error occur:
System.ApplicationException: Package name is required. Please pass at least one package name to uninstall.
   at chocolatey.infrastructure.app.commands.ChocolateyUninstallCommand.handle_validation(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<>c__DisplayClasse.<run>b__6()
   at chocolatey.infrastructure.app.configuration.ConfigurationOptions.parse_arguments_and_update_configuration(ICollection`1 args, ChocolateyConfiguration configuration, Action`1 setOptions, Action`1 afterParse, Action validateConfiguration, Action helpMessage)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<run>b__3(ICommand command)
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2020-04-29 20:06:23,843 38580 [DEBUG] - Exiting with 1
2020-04-29 20:06:43,196 37052 [DEBUG] - XmlConfiguration is now operational
2020-04-29 20:06:43,226 37052 [INFO ] - ============================================================
2020-04-29 20:06:43,341 37052 [INFO ] - Chocolatey v0.10.15
2020-04-29 20:06:43,361 37052:1 [DEBUG] - Chocolatey is running on Windows v 10.0.19041.0 - :Main:0 
2020-04-29 20:06:43,371 37052:1 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old". - :delete_file:0 
2020-04-29 20:06:43,371 37052:1 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old". - :delete_file:0 
2020-04-29 20:06:43,378 37052:1 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" uninstall nodejs --debug --trace - :run:0 
2020-04-29 20:06:43,380 37052:1 [DEBUG] - Received arguments: uninstall nodejs --debug --trace - :run:0 
2020-04-29 20:06:43,413 37052:1 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage. - :run:0 
2020-04-29 20:06:43,418 37052:1 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers... - :publish:0 
2020-04-29 20:06:43,423 37052:1 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed... - :handle_message:0 
2020-04-29 20:06:43,465 37052:1 [DEBUG] - Performing validation checks. - :<run>b__6:0 
2020-04-29 20:06:43,469 37052:1 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers... - :publish:0 
2020-04-29 20:06:43,477 37052:1 [ERROR] - Chocolatey had an error occur:
System.ApplicationException: Package name is required. Please pass at least one package name to uninstall.
   at chocolatey.infrastructure.app.commands.ChocolateyUninstallCommand.handle_validation(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<>c__DisplayClasse.<run>b__6()
   at chocolatey.infrastructure.app.configuration.ConfigurationOptions.parse_arguments_and_update_configuration(ICollection`1 args, ChocolateyConfiguration configuration, Action`1 setOptions, Action`1 afterParse, Action validateConfiguration, Action helpMessage)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<run>b__3(ICommand command)
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args) - :Main:0 
2020-04-29 20:06:43,482 37052:1 [DEBUG] - Exiting with 1 - :Main:0 
2020-04-29 20:06:54,853 44380 [DEBUG] - XmlConfiguration is now operational
2020-04-29 20:06:54,884 44380 [INFO ] - ============================================================
2020-04-29 20:06:54,997 44380 [INFO ] - Chocolatey v0.10.15
2020-04-29 20:06:55,004 44380 [DEBUG] - Chocolatey is running on Windows v 10.0.19041.0
2020-04-29 20:06:55,007 44380 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2020-04-29 20:06:55,009 44380 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2020-04-29 20:06:55,015 44380 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" uninstall nodejs --debug --verbose
2020-04-29 20:06:55,017 44380 [DEBUG] - Received arguments: uninstall nodejs --debug --verbose
2020-04-29 20:06:55,049 44380 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2020-04-29 20:06:55,056 44380 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2020-04-29 20:06:55,062 44380 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2020-04-29 20:06:55,101 44380 [DEBUG] - Performing validation checks.
2020-04-29 20:06:55,104 44380 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-04-29 20:06:55,114 44380 [ERROR] - Chocolatey had an error occur:
System.ApplicationException: Package name is required. Please pass at least one package name to uninstall.
   at chocolatey.infrastructure.app.commands.ChocolateyUninstallCommand.handle_validation(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<>c__DisplayClasse.<run>b__6()
   at chocolatey.infrastructure.app.configuration.ConfigurationOptions.parse_arguments_and_update_configuration(ICollection`1 args, ChocolateyConfiguration configuration, Action`1 setOptions, Action`1 afterParse, Action validateConfiguration, Action helpMessage)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.<>c__DisplayClassc.<run>b__3(ICommand command)
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2020-04-29 20:06:55,118 44380 [DEBUG] - Exiting with 1

~~~

</p>

</details>

**Comment by ferventcoder** [comment]
Well this is really weird. I'm actually not seeing anything here that tells me why this is behaving like this. You see this with every call to choco uninstall? 

Normally we see more information from the logs about how it set configuration prior to validation, but I'm not really seeing that either - I did see this `Input='-'` and that is definitely weird. What kind of shell are you running in?

**Comment by altwohill** [comment]
I agree it's weird! This is just powershell. The only non-standard thing I can think of is I'm running an Insider ring; on Windows 10 Version 2004 Build 19041.264

**Comment by ferventcoder** [comment]
We need to inspect this before next release for sure.

**Comment by altwohill** [comment]
Just an update on this, it appears to affect `install` as well. But not `search``?

![image](https://user-images.githubusercontent.com/629254/84076328-a6f9ef00-aa29-11ea-82e5-ff28155374aa.png)

**Comment by ferventcoder** [comment]
@altwohill sorry to have to ask, but can you try reinstalling Chocolatey?

**Comment by altwohill** [comment]
By reinstall I take it you mean delete C:\ProgramData\Chocolatey and then re-run the installer script? 
Done - same result :/

**Comment by ferventcoder** [comment]
I didn't mean a need to delete the entire directory, only certain parts. Unfortunately we are not seeing other folks reporting this and choco is used on many many systems. 

Without a way to reproduce the issue, we will be unable to supply a fix. 

Try moving to cmd.exe and see if that gives you the same error.

**Comment by altwohill** [comment]
Same result unfortunately 
![image](https://user-images.githubusercontent.com/629254/86225461-5f0c5900-bbde-11ea-8fb0-f14aef19757e.png)

**Comment by AdmiringWorm** [comment]
@altwohill I just want to make sure that the call isn't intercepted by a different program which calls chocolatey incorrectly, and/or the shim isn't corrupted in some way.

Can you try calling the choco executable with its full path
The full path should be
`C:\ProgramData\chocolatey\choco.exe`

If this works, then it points to either a different executable somewhere (use `where.exe` to find it), or a corrupt shim (not sure how the shim can be regenerated for the end-user though).

**Comment by altwohill** [comment]
Using the full path doesn't change anything 

![image](https://user-images.githubusercontent.com/629254/86333903-a5c28780-bca0-11ea-891d-6283978b0d4e.png)

**Comment by pauby** [comment]
@altwohill Without being able to reproduce this issue there isn't much we can work with to resolve this. The issue _appears_ to be isolated to your environment. The link from @mdelapenya goes to a Jenkins log that has now been removed and this could also be environment related.

Without the ability to reproduce this I'm going to go ahead and close the issue. If you have additional information, or you can reproduce it we can always re-open.
