### ISSUE TITLE
Getting 409 Conflict when there is no clonflict

### ISSUE THREAD

**Issue by isaacrlevin** [chocolatey/choco#2041]
### What You Are Seeing?
409 Conflict when trying to push even though there are no existing Packages with this name

### What is Expected?
Package gets pushed

### How Did You Get This To Happen? (Steps to Reproduce)
choco.exe push C:\Users\islevin\Downloads\PresenceLight.1.0.144.nupkg --source https://push.chocolatey.org/

### Output Log
````
Chocolatey is running on Windows v 10.0.19041.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line not shown - sensitive arguments may have been passed.
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Checked
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://push.chocolatey.org/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='push'|
CacheLocation='C:\Users\islevin\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://push.chocolatey.org/'|SourceType='normal'|
Debug='True'|
Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|
Input='C:\Users\islevin\Downloads\PresenceLight.1.0.144.nupkg'|
AllVersions='False'|SkipPackageInstallProvider='False'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19041.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='islevin'|
Information.UserDomainName='NORTHAMERICA'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Users\islevin\Downloads'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyPushCommand - Normal Run Mode _
Attempting to push PresenceLight.1.0.144.nupkg to https://push.chocolatey.org/
PUT https://push.chocolatey.org/api/v2/package/
Sending message 'PostRunMessage' out if there are subscribers...
Chocolatey had an error occur:
System.ApplicationException: An error has occurred. It's possible the package version already exists on the repository. ---> System.InvalidOperationException: Failed to process request. 'This package had an issue pushing: Exception of type 'System.OutOfMemoryException' was thrown.'.
The remote server returned an error: (409) Conflict.. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   --- End of inner exception stack trace ---
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   --- End of inner exception stack trace ---
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   at chocolatey.infrastructure.app.services.NugetService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
Exiting with 1
````

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
2020-05-01 11:49:24,668 11644 [DEBUG] - XmlConfiguration is now operational
2020-05-01 11:49:24,705 11644 [INFO ] - ============================================================
2020-05-01 11:49:24,864 11644 [INFO ] - Chocolatey v0.10.15
2020-05-01 11:49:24,873 11644 [DEBUG] - Chocolatey is running on Windows v 10.0.19041.0
2020-05-01 11:49:24,878 11644 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2020-05-01 11:49:24,880 11644 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2020-05-01 11:49:24,895 11644 [DEBUG] - Command line not shown - sensitive arguments may have been passed.
2020-05-01 11:49:24,959 11644 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2020-05-01 11:49:24,968 11644 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2020-05-01 11:49:24,982 11644 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2020-05-01 11:49:25,044 11644 [DEBUG] - Performing validation checks.
2020-05-01 11:49:25,049 11644 [DEBUG] - Global Configuration Validation Checks:
2020-05-01 11:49:25,052 11644 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2020-05-01 11:49:25,055 11644 [DEBUG] - System State Validation Checks:
2020-05-01 11:49:25,060 11644 [DEBUG] -  Reboot Requirement Checks:
2020-05-01 11:49:25,066 11644 [DEBUG] -  - Pending Computer Rename = Checked
2020-05-01 11:49:25,070 11644 [DEBUG] -  - Pending Component Based Servicing = Checked
2020-05-01 11:49:25,074 11644 [DEBUG] -  - Pending Windows Auto Update = Checked
2020-05-01 11:49:25,077 11644 [DEBUG] -  - Pending File Rename Operations = Checked
2020-05-01 11:49:25,079 11644 [DEBUG] -  - Pending Windows Package Installer = Checked
2020-05-01 11:49:25,081 11644 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2020-05-01 11:49:25,085 11644 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2020-05-01 11:49:25,087 11644 [DEBUG] - The source 'https://push.chocolatey.org/' evaluated to a 'normal' source type
2020-05-01 11:49:25,090 11644 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2020-05-01 11:49:25,109 11644 [DEBUG] - Configuration: CommandName='push'|
CacheLocation='C:\Users\islevin\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://push.chocolatey.org/'|SourceType='normal'|
Debug='True'|
Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|
Input='C:\Users\islevin\Downloads\PresenceLight.1.0.144.nupkg'|
AllVersions='False'|SkipPackageInstallProvider='False'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19041.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='islevin'|
Information.UserDomainName='NORTHAMERICA'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Users\islevin\Downloads'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2020-05-01 11:49:25,122 11644 [DEBUG] - _ Chocolatey:ChocolateyPushCommand - Normal Run Mode _
2020-05-01 11:49:25,131 11644 [INFO ] - Attempting to push PresenceLight.1.0.144.nupkg to https://push.chocolatey.org/
2020-05-01 11:49:25,371 11644 [INFO ] - PUT https://push.chocolatey.org/api/v2/package/
2020-05-01 11:49:36,730 11644 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2020-05-01 11:49:36,743 11644 [ERROR] - Chocolatey had an error occur:
System.ApplicationException: An error has occurred. It's possible the package version already exists on the repository. ---> System.InvalidOperationException: Failed to process request. 'This package had an issue pushing: Exception of type 'System.OutOfMemoryException' was thrown.'. 
The remote server returned an error: (409) Conflict.. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   --- End of inner exception stack trace ---
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeout, Boolean disableBuffering)
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   --- End of inner exception stack trace ---
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   at chocolatey.infrastructure.app.services.NugetService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2020-05-01 11:49:36,746 11644 [DEBUG] - Exiting with 1
~~~

</p>

</details>

**Comment by isaacrlevin** [comment]
Closing, dupe https://github.com/chocolatey/chocolatey.org/issues/613

**Comment by sascha-wi** [comment]
I know I am asking too much, but this link leads nowhere. Its a bit ridicolous imo

**Comment by JPRuskin** [comment]
> I know I am asking too much, but this link leads nowhere. Its a bit ridicolous imo

I believe that was an accurate link five years ago when the comment was made, but the repository has been renamed and made private since then.

**Comment by corbob** [comment]
@sascha-wi assuming you're seeing this error, you're probably more interested in this [docs issue](https://github.com/chocolatey/docs/issues/426) to document causes of the 409 (among others). In particular this comment that lists a few of the known causes for 409: https://github.com/chocolatey/docs/issues/426#issuecomment-1102966442
