### ISSUE TITLE
Upgrade crashes on specific package due to invalid base64

### ISSUE THREAD

**Issue by Terrance** [chocolatey/choco#2216]
### What You Are Seeing?

`choco upgrade` crashes upon encountering a specific package (in this case `keepass-rpc`):

```
PS C:\WINDOWS\system32> choco upgrade keepass-rpc
Chocolatey v0.10.15
Upgrading the following packages:
keepass-rpc
By upgrading you accept licenses for the packages.

You have keepass-rpc v1.14.0 installed. Version 1.14.0.20210127 is available based on your source(s).

Chocolatey upgraded 0/0 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
```

I'm assuming this is a package-specific issue, though as I don't know which base64 string it's referring to, it could alternatively be some internal state.

In any case, a package broken in this way ought not to crash Chocolately outright -- `choco upgrade all` exits here, instead of proceeding to upgrade the rest of my packages, and ChocolateyGUI also fails to start entirely (presumably because it's calling `choco` under the hood).

### What is Expected?

Packages in this state should be caught, and an error displayed.

### How Did You Get This To Happen? (Steps to Reproduce)

It's been a problem for me since keepass-rpc was updated past v1.14.0 (the version I have installed currently).  I don't have another machine to test on, so I haven't yet tried reinstalling the package in case there's something more I can provide in terms of the current state.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
2021-03-18 22:15:10,692 20508 [DEBUG] - XmlConfiguration is now operational
2021-03-18 22:15:10,722 20508 [INFO ] - ============================================================
2021-03-18 22:15:10,838 20508 [INFO ] - Chocolatey v0.10.15
2021-03-18 22:15:10,844 20508 [DEBUG] - Chocolatey is running on Windows v 10.0.19042.0
2021-03-18 22:15:10,846 20508 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2021-03-18 22:15:10,847 20508 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2021-03-18 22:15:10,856 20508 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade -dv keepass-rpc
2021-03-18 22:15:10,857 20508 [DEBUG] - Received arguments: upgrade -dv keepass-rpc
2021-03-18 22:15:10,889 20508 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2021-03-18 22:15:10,895 20508 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2021-03-18 22:15:10,900 20508 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2021-03-18 22:15:10,954 20508 [DEBUG] - Performing validation checks.
2021-03-18 22:15:10,959 20508 [DEBUG] - Global Configuration Validation Checks:
2021-03-18 22:15:10,962 20508 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2021-03-18 22:15:10,964 20508 [DEBUG] - System State Validation Checks:
2021-03-18 22:15:10,969 20508 [DEBUG] -  Reboot Requirement Checks:
2021-03-18 22:15:10,975 20508 [DEBUG] -  - Pending Computer Rename = Checked
2021-03-18 22:15:10,977 20508 [DEBUG] -  - Pending Component Based Servicing = Checked
2021-03-18 22:15:10,979 20508 [DEBUG] -  - Pending Windows Auto Update = Checked
2021-03-18 22:15:10,981 20508 [DEBUG] -  - Pending File Rename Operations = Ignored
2021-03-18 22:15:10,983 20508 [DEBUG] -  - Pending Windows Package Installer = Checked
2021-03-18 22:15:10,984 20508 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2021-03-18 22:15:10,991 20508 [INFO ] - 2 validations performed. 2 success(es), 0 warning(s), and 0 error(s).
2021-03-18 22:15:10,992 20508 [DEBUG] - The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2021-03-18 22:15:10,994 20508 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2021-03-18 22:15:11,006 20508 [DEBUG] - Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\User\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='keepass-rpc'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='keepass-rpc'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.19042.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='User'|Information.UserDomainName='HOSTNAME'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\WINDOWS\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='True'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2021-03-18 22:15:11,022 20508 [DEBUG] - _ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
2021-03-18 22:15:11,028 20508 [INFO ] - Upgrading the following packages:
2021-03-18 22:15:11,035 20508 [INFO ] - keepass-rpc
2021-03-18 22:15:11,037 20508 [INFO ] - By upgrading you accept licenses for the packages.
2021-03-18 22:15:11,154 20508 [DEBUG] - Using 'https://chocolatey.org/api/v2/'.
2021-03-18 22:15:11,569 20508 [DEBUG] - - Supports prereleases? 'True'.
2021-03-18 22:15:11,572 20508 [DEBUG] - - Is ServiceBased? 'True'.
2021-03-18 22:15:11,913 20508 [DEBUG] - Package 'keepass-rpc' found on source 'https://chocolatey.org/api/v2/'
2021-03-18 22:15:11,918 20508 [WARN ] - 
You have keepass-rpc v1.14.0 installed. Version 1.14.0.20210127 is available based on your source(s).
2021-03-18 22:15:11,928 20508 [WARN ] - 
Chocolatey upgraded 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2021-03-18 22:15:11,932 20508 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2021-03-18 22:15:11,938 20508 [ERROR] - The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
2021-03-18 22:15:11,955 20508 [ERROR] - More Details: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at chocolatey.infrastructure.cryptography.DefaultEncryptionUtility.decrypt_string(String encryptedString)
   at chocolatey.infrastructure.app.services.NugetService.set_package_config_for_upgrade(ChocolateyConfiguration config, ChocolateyPackageInformation packageInfo)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Boolean performAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.upgrade_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2021-03-18 22:15:11,956 20508 [DEBUG] - Exiting with 1
~~~

</p>

</details>

**Comment by AdmiringWorm** [comment]
I don't think it is the package itself that is the problem, and I tested the package, which worked on my end as it should (although I used the 0.10.16 beta version).
I think the Base64 is either an internal state, the response from upstream or an encrypted/obfuscated configuration file.

I suspect you may have encountered a temporary network issue that gave you the wrong response, a hard drive issue or a corrupt configuration file.
If you haven't already, I would suggest to try installing the package again.

**Comment by Terrance** [comment]
I've been working around this for a few weeks now, so I guess whatever malformed state I had was already stored locally.  In any case I've uninstalled and reinstalled the package, and things seems to be fine again now.

**Comment by corbob** [comment]
@Terrance it sounds like you've resolved this issue for yourself. As such I'll go ahead and close this. If this is incorrect, please feel free to reply and we can reopen it and perhaps gather more detailed logs.

**Comment by Terrance** [comment]
I haven't (re-)encountered this with keepass-rpc or any other package (though I'm now mainly using Chocolatey GUI rather than the CLI directly).

If it was indeed down to a corrupt file or invalid HTTP response somewhere at the time, it would have been (and still would be) useful to have a nicer error message suggesting where it went wrong, but if you can't deduce that from the log then there's probably not much more that can be done here.

**Comment by Tricky1975** [comment]
I'm currently experiencing this error, apparently in Lua (see screenshot). However trying to uninstall and re-install Lua wouldn't work. As a matter of fact, trying to uninstall pops up the same error. Am I experiencing the same issue Terrance did (but on a different package) or it the error message being the same a coincidence and that I'm suffering from a different issue?
![image](https://github.com/chocolatey/choco/assets/11202073/c9d07cdd-eda8-4f8c-8538-bf947d56fbed)

**Comment by pauby** [comment]
@Tricky1975 this issue is closed and is not being monitored. Please raise a new issue.

**Comment by Tricky1975** [comment]
Will do.

**Comment by slarys728** [comment]
I have same problem like @Tricky1975. Any solution has been found?

**Comment by pauby** [comment]
Please see the earlier comments.
