### ISSUE TITLE
"Second path fragment must not be a drive or UNC name" Error when trying to uninstall python3.6

### ISSUE THREAD

**Issue by PhilippSelenium** [chocolatey/choco#2222]
### What You Are Seeing?

```
2021-04-01 09:32:21,543 26920 [ERROR] - Second path fragment must not be a drive or UNC name.
Parameter name: path2
2021-04-01 09:32:21,546 26920 [ERROR] - More Details: System.ArgumentException: Second path fragment must not be a drive or UNC name.
Parameter name: path2
   at System.IO.Path.InternalCombine(String path1, String path2)
   at System.IO.FileSystemEnumerableIterator`1.GetFullSearchString(String fullPath, String searchPattern)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.PhysicalFileSystem.GetFiles(String path, String filter, Boolean recursive)
   at NuGet.LocalPackageRepository.<GetPackageFiles>d__31.MoveNext()
   at NuGet.LocalPackageRepository.<GetPackages>d__28.MoveNext()
   at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
   at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
   at chocolatey.infrastructure.app.services.NugetService.uninstall_run(ChocolateyConfiguration config, Action`1 continueAction, Boolean performAction, Action`1 beforeUninstallAction)
   at chocolatey.infrastructure.app.services.NugetService.uninstall_run(ChocolateyConfiguration config, Action`1 continueAction, Action`1 beforeUninstallAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.uninstall_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2021-04-01 09:32:21,546 26920 [DEBUG] - Exiting with 1
```

### What is Expected?

No Error

### How Did You Get This To Happen? (Steps to Reproduce)

```
C:\\ProgramData\\chocolatey\\bin\\choco.exe uninstall python3 --yes --no-progress --limit-output --package-params /InstallDir:C:\\Python36 --timeout 2700  --version 3.6.8
```
results in the error from above

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
2021-04-01 09:46:29,481 27024 [DEBUG] - XmlConfiguration is now operational
2021-04-01 09:46:29,518 27024 [INFO ] - ============================================================
2021-04-01 09:46:29,695 27024 [DEBUG] - Chocolatey is running on Windows v 10.0.18363.0
2021-04-01 09:46:29,698 27024 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2021-04-01 09:46:29,699 27024 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2021-04-01 09:46:29,710 27024 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" uninstall python3 --yes --no-progress --limit-output --package-params /InstallDir:C:\\Python36 --timeout 2700 --debug --verbose --version 3.6.8
2021-04-01 09:46:29,712 27024 [DEBUG] - Received arguments: uninstall python3 --yes --no-progress --limit-output --package-params /InstallDir:C:\\Python36 --timeout 2700 --debug --verbose --version 3.6.8
2021-04-01 09:46:29,753 27024 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2021-04-01 09:46:29,759 27024 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2021-04-01 09:46:29,765 27024 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2021-04-01 09:46:29,821 27024 [DEBUG] - Performing validation checks.
2021-04-01 09:46:29,825 27024 [DEBUG] - Global Configuration Validation Checks:
2021-04-01 09:46:29,826 27024 [DEBUG] -  - Package Exit Code / Exit On Reboot = Checked
2021-04-01 09:46:29,828 27024 [DEBUG] - System State Validation Checks:
2021-04-01 09:46:29,829 27024 [DEBUG] -  Reboot Requirement Checks:
2021-04-01 09:46:29,832 27024 [DEBUG] -  - Pending Computer Rename = Checked
2021-04-01 09:46:29,833 27024 [DEBUG] -  - Pending Component Based Servicing = Checked
2021-04-01 09:46:29,834 27024 [DEBUG] -  - Pending Windows Auto Update = Checked
2021-04-01 09:46:29,835 27024 [DEBUG] -  - Pending File Rename Operations = Ignored
2021-04-01 09:46:29,837 27024 [DEBUG] -  - Pending Windows Package Installer = Checked
2021-04-01 09:46:29,838 27024 [DEBUG] -  - Pending Windows Package Installer SysWow64 = Checked
2021-04-01 09:46:29,842 27024 [DEBUG] - The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2021-04-01 09:46:29,843 27024 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
2021-04-01 09:46:29,853 27024 [DEBUG] - Configuration: CommandName='uninstall'|
CacheLocation='C:\Users\buibot00\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='True'|Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|
RegularOutput='False'|
QuietOutput='False'|PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='False'|
Input='python3 --package-params /InstallDir:C:\\Python36'|
Version='3.6.8'|AllVersions='False'|SkipPackageInstallProvider='False'|
PackageNames='python3;/InstallDir:C:\\Python36'|Prerelease='False'|
ForceX86='False'|OverrideArguments='False'|NotSilent='False'|
ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.18363.0'|
Information.PlatformName='Windows 10'|
Information.ChocolateyVersion='0.10.15.0'|
Information.ChocolateyProductVersion='0.10.15'|
Information.FullName='choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='buibot00'|Information.UserDomainName='EMBVBOT21'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\WINDOWS\system32'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='False'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|Proxy.BypassOnLocal='True'|
2021-04-01 09:46:29,863 27024 [DEBUG] - _ Chocolatey:ChocolateyUninstallCommand - Normal Run Mode _
2021-04-01 09:46:29,868 27024 [INFO ] - Uninstalling the following packages:
2021-04-01 09:46:29,869 27024 [INFO ] - python3;/InstallDir:C:\\Python36
2021-04-01 09:46:30,073 27024 [DEBUG] - python3 3.6.8
2021-04-01 09:46:30,137 27024 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\python3".
2021-04-01 09:46:30,142 27024 [DEBUG] - Backing up existing python3 prior to operation.
2021-04-01 09:46:30,144 27024 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\python3'
 to 'C:\ProgramData\chocolatey\lib-bkp\python3'
2021-04-01 09:46:32,149 27024 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\python3".
2021-04-01 09:46:35,374 27024 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\python3\python3.nupkg"
 to "C:\ProgramData\chocolatey\lib\python3\python3.nupkg".
2021-04-01 09:46:35,456 27024 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\python3\python3.nuspec"
 to "C:\ProgramData\chocolatey\lib\python3\python3.nuspec".
2021-04-01 09:46:35,458 27024 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\python3\legal".
2021-04-01 09:46:35,459 27024 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\python3\legal\LICENSE.txt"
 to "C:\ProgramData\chocolatey\lib\python3\legal\LICENSE.txt".
2021-04-01 09:46:35,460 27024 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\python3\legal\VERIFICATION.txt"
 to "C:\ProgramData\chocolatey\lib\python3\legal\VERIFICATION.txt".
2021-04-01 09:46:35,462 27024 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib\python3\tools".
2021-04-01 09:46:35,463 27024 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\python3\tools\chocolateyInstall.ps1"
 to "C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1".
2021-04-01 09:46:35,464 27024 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib-bkp\python3\tools\python-3.6.8-amd64.exe.ignore"
 to "C:\ProgramData\chocolatey\lib\python3\tools\python-3.6.8-amd64.exe.ignore".
2021-04-01 09:46:36,970 27024 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\python3'
2021-04-01 09:46:37,194 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\python3.nupkg'
  with checksum '9F0F2F85010DD74E82812DEFA14F0C87'
2021-04-01 09:46:37,196 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\python3.nuspec'
  with checksum '87339C4AA9D5D769C05B1573FDFC5546'
2021-04-01 09:46:37,197 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\legal\LICENSE.txt'
  with checksum '3FBFBB88B1C6F11A666EB20C490B6DD6'
2021-04-01 09:46:37,198 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\legal\VERIFICATION.txt'
  with checksum '29534D687B7E89FB472664798DFDF5B5'
2021-04-01 09:46:37,200 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\tools\chocolateyInstall.ps1'
  with checksum '7FF1D4A2DCB8A095EDAD930A61AE3CE6'
2021-04-01 09:46:37,201 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\tools\python-3.6.8-amd64.exe.ignore'
  with checksum 'BEA07E6D2B8DCE396FE21BAA61B34956'
2021-04-01 09:46:37,942 27024 [INFO ] - [NuGet] Uninstalling 'python3 3.6.8'.
2021-04-01 09:46:37,945 27024 [INFO ] - 
python3 v3.6.8
2021-04-01 09:46:37,956 27024 [INFO ] -  Running auto uninstaller...
2021-04-01 09:46:37,957 27024 [DEBUG] -   Sleeping for 2 seconds to allow Windows to finish cleaning up.
2021-04-01 09:46:39,970 27024 [DEBUG] -  Preparing uninstall key '"C:\Users\buibot00\AppData\Local\Package Cache\{1aa5398d-0cf8-49e6-adb0-86365145c01c}\python-3.6.8-amd64.exe" /uninstall /quiet' for 'Python 3.6.8 (64-bit)'
2021-04-01 09:46:40,139 27024 [DEBUG] -  Uninstaller path is 'C:\Users\buibot00\AppData\Local\Package Cache\{1aa5398d-0cf8-49e6-adb0-86365145c01c}\python-3.6.8-amd64.exe'
2021-04-01 09:46:40,141 27024 [DEBUG] -  Installer type is 'CustomInstaller'
2021-04-01 09:46:40,141 27024 [DEBUG] -  Setting up uninstall logging directory at C:\Users\buibot00\AppData\Local\Temp\chocolatey\python3\3.6.8
2021-04-01 09:46:40,142 27024 [DEBUG] -  Args are '/uninstall /quiet'
2021-04-01 09:46:40,146 27024 [DEBUG] - Calling command ['"C:\Users\buibot00\AppData\Local\Package Cache\{1aa5398d-0cf8-49e6-adb0-86365145c01c}\python-3.6.8-amd64.exe" /uninstall /quiet']
2021-04-01 09:47:08,088 27024 [DEBUG] - Command ['"C:\Users\buibot00\AppData\Local\Package Cache\{1aa5398d-0cf8-49e6-adb0-86365145c01c}\python-3.6.8-amd64.exe" /uninstall /quiet'] exited with '0'
2021-04-01 09:47:08,093 27024 [INFO ] -  Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
2021-04-01 09:47:08,096 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{1F5F06E6-A6C0-482E-8FEB-681DE2059228}' for 'Python 3.6.8 Utility Scripts (64-bit)'
2021-04-01 09:47:08,246 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Utility Scripts (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:08,248 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:08,382 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{1F5F06E6-A6C0-482E-8FEB-681DE2059228}' value 'InstallLocation' - found? False
2021-04-01 09:47:08,383 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{290348F2-D9D3-470E-9858-22F0F74E3623}' for 'Python 3.6.8 Core Interpreter (64-bit)'
2021-04-01 09:47:08,519 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Core Interpreter (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:08,520 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:08,655 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{290348F2-D9D3-470E-9858-22F0F74E3623}' value 'InstallLocation' - found? False
2021-04-01 09:47:08,657 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{315736CC-5A10-4E28-AE50-78BD74EF0346}' for 'Python 3.6.8 Test Suite (64-bit)'
2021-04-01 09:47:08,788 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Test Suite (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:08,790 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:08,923 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{315736CC-5A10-4E28-AE50-78BD74EF0346}' value 'InstallLocation' - found? False
2021-04-01 09:47:08,928 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{4BFF1147-97F2-432E-AD26-2224B609957C}' for 'Python 3.6.8 Standard Library (64-bit)'
2021-04-01 09:47:09,080 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Standard Library (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:09,085 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:09,226 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{4BFF1147-97F2-432E-AD26-2224B609957C}' value 'InstallLocation' - found? False
2021-04-01 09:47:09,230 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{73EE519A-D901-4844-8E8F-C635705A2414}' for 'Python 3.6.8 Documentation (64-bit)'
2021-04-01 09:47:09,375 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Documentation (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:09,380 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:09,517 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{73EE519A-D901-4844-8E8F-C635705A2414}' value 'InstallLocation' - found? False
2021-04-01 09:47:09,522 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{832D6876-0624-476C-B5CE-B8067336BC9D}' for 'Python 3.6.8 Add to Path (64-bit)'
2021-04-01 09:47:09,666 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Add to Path (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:09,670 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:09,805 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{832D6876-0624-476C-B5CE-B8067336BC9D}' value 'InstallLocation' - found? False
2021-04-01 09:47:09,809 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{A43B98B0-5A92-4EBA-929D-FE0A840CD97A}' for 'Python 3.6.8 Development Libraries (64-bit)'
2021-04-01 09:47:09,945 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Development Libraries (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:09,949 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:10,089 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{A43B98B0-5A92-4EBA-929D-FE0A840CD97A}' value 'InstallLocation' - found? False
2021-04-01 09:47:10,093 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{C48DD541-2669-499A-B7AB-EC0504307601}' for 'Python 3.6.8 pip Bootstrap (64-bit)'
2021-04-01 09:47:10,229 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 pip Bootstrap (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:10,234 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:10,366 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{C48DD541-2669-499A-B7AB-EC0504307601}' value 'InstallLocation' - found? False
2021-04-01 09:47:10,371 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{E1155302-B578-4D8C-8431-FAE677FBC58C}' for 'Python 3.6.8 Executables (64-bit)'
2021-04-01 09:47:10,508 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Executables (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:10,512 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:10,658 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{E1155302-B578-4D8C-8431-FAE677FBC58C}' value 'InstallLocation' - found? False
2021-04-01 09:47:10,663 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /I{EBD78311-1837-4432-94EE-5A5E5E206888}' for 'Python 3.6.8 Tcl/Tk Support (64-bit)'
2021-04-01 09:47:10,797 27024 [INFO ] -  Skipping auto uninstaller - 'Python 3.6.8 Tcl/Tk Support (64-bit)' appears to have been uninstalled already by other means.
2021-04-01 09:47:10,801 27024 [DEBUG] -  Searched for install path '' - found? False
2021-04-01 09:47:10,937 27024 [DEBUG] -  Searched for registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{EBD78311-1837-4432-94EE-5A5E5E206888}' value 'InstallLocation' - found? False
2021-04-01 09:47:10,942 27024 [DEBUG] -  Preparing uninstall key 'MsiExec.exe /X{3187A5F8-59A0-4587-885C-7748FF5D1F13}' for 'Python Launcher'
2021-04-01 09:47:11,081 27024 [DEBUG] -  Uninstaller path is 'MsiExec.exe'
2021-04-01 09:47:11,086 27024 [DEBUG] -  Installer type is 'MsiInstaller'
2021-04-01 09:47:11,087 27024 [DEBUG] -  Setting up uninstall logging directory at C:\Users\buibot00\AppData\Local\Temp\chocolatey\python3\3.6.8
2021-04-01 09:47:11,089 27024 [DEBUG] -  Args are '/X{3187A5F8-59A0-4587-885C-7748FF5D1F13} /qn /norestart'
2021-04-01 09:47:11,090 27024 [DEBUG] - Calling command ['"MsiExec.exe" /X{3187A5F8-59A0-4587-885C-7748FF5D1F13} /qn /norestart']
2021-04-01 09:47:11,355 27024 [DEBUG] - Command ['"MsiExec.exe" /X{3187A5F8-59A0-4587-885C-7748FF5D1F13} /qn /norestart'] exited with '0'
2021-04-01 09:47:11,359 27024 [INFO ] -  Auto uninstaller has successfully uninstalled python3 or detected previous uninstall.
2021-04-01 09:47:11,361 27024 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2021-04-01 09:47:11,406 27024 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
2021-04-01 09:47:11,411 27024 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\python3".
2021-04-01 09:47:11,426 27024 [DEBUG] - [NuGet] Removed file 'LICENSE.txt' to folder 'C:\ProgramData\chocolatey\lib\python3\legal'.
2021-04-01 09:47:11,428 27024 [DEBUG] - [NuGet] Removed file 'VERIFICATION.txt' to folder 'C:\ProgramData\chocolatey\lib\python3\legal'.
2021-04-01 09:47:11,434 27024 [DEBUG] - [NuGet] Removed folder 'C:\ProgramData\chocolatey\lib\python3\legal'.
2021-04-01 09:47:11,436 27024 [DEBUG] - [NuGet] Removed file 'chocolateyInstall.ps1' to folder 'C:\ProgramData\chocolatey\lib\python3\tools'.
2021-04-01 09:47:11,438 27024 [DEBUG] - [NuGet] Removed file 'python3.nuspec' to folder 'C:\ProgramData\chocolatey\lib\python3'.
2021-04-01 09:47:11,445 27024 [DEBUG] - [NuGet] Removed file 'python3.nupkg' to folder 'C:\ProgramData\chocolatey\lib\python3'.
2021-04-01 09:47:11,448 27024 [DEBUG] - [NuGet] The directory is not empty.

2021-04-01 09:47:11,449 27024 [INFO ] - [NuGet] Successfully uninstalled 'python3 3.6.8'.
2021-04-01 09:47:11,462 27024 [INFO ] -  python3 has been successfully uninstalled.
2021-04-01 09:47:11,467 27024 [DEBUG] - Removing nupkg if it still exists.
2021-04-01 09:47:11,471 27024 [DEBUG] - Ensuring removal of installation files.
2021-04-01 09:47:11,473 27024 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\python3\tools\python-3.6.8-amd64.exe.ignore'
  with checksum 'BEA07E6D2B8DCE396FE21BAA61B34956'
2021-04-01 09:47:11,477 27024 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\python3\tools\python-3.6.8-amd64.exe.ignore".
2021-04-01 09:47:11,479 27024 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib\python3".
2021-04-01 09:47:11,481 27024 [DEBUG] - Ensuring removal of package cache files.
2021-04-01 09:47:11,495 27024 [WARN ] - 
Chocolatey uninstalled 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2021-04-01 09:47:11,500 27024 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2021-04-01 09:47:11,526 27024 [ERROR] - Chocolatey had an error occur:
System.ArgumentException: Second path fragment must not be a drive or UNC name.
Parameter name: path2
   at System.IO.Path.InternalCombine(String path1, String path2)
   at System.IO.FileSystemEnumerableIterator`1.GetFullSearchString(String fullPath, String searchPattern)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.PhysicalFileSystem.GetFiles(String path, String filter, Boolean recursive)
   at NuGet.LocalPackageRepository.<GetPackageFiles>d__31.MoveNext()
   at NuGet.LocalPackageRepository.<GetPackages>d__28.MoveNext()
   at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
   at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
   at chocolatey.infrastructure.app.services.NugetService.uninstall_run(ChocolateyConfiguration config, Action`1 continueAction, Boolean performAction, Action`1 beforeUninstallAction)
   at chocolatey.infrastructure.app.services.NugetService.uninstall_run(ChocolateyConfiguration config, Action`1 continueAction, Action`1 beforeUninstallAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.uninstall_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2021-04-01 09:47:11,544 27024 [DEBUG] - Exiting with 1

~~~

</p>

</details>

**Comment by nativeit** [comment]
Since no one else has commented on this, the issue is almost certainly with using the system drive within the argument `--package-params /InstallDir:C:\\Python36`. Try wrapping the path in quotes rather than using the `\` escape character. For example:

```
C:\ProgramData\chocolatey\bin\choco.exe uninstall python3 --yes --no-progress --limit-output --package-params "/InstallDir:'C:\Python36'" --timeout 2700  --version 3.6.8
```

I don't have the licensed version of Chocolatey to test the `/InstallDir` argument, so I can't say for sure that works.

**Comment by TheCakeIsNaOH** [comment]
> I don't have the licensed version of Chocolatey to test the /InstallDir argument, so I can't say for sure that works.

Open source versions of Chocolatey can use `--package-params`, including `/InstallDir` for Python. The package parameters are manually implemented inside a package's `chocolateyInstall.ps1` script, so open source Chocolatey can use any parameters made available by a package.

The thing that the licensed versions of Chocolatey have is the `--install-directory` argument, were the licensed extension will try to figure out the correct argument to pass to the installer and automatically pass that argument, no need for a manual implementation in the `chocolateyInstall.ps1`

> Try wrapping the path in quotes

Yes, that is most likely the issue. Here is what follows best practices for passing arguments:
`--package-parameters="'/InstallDir:C:\Python36'"

(See `choco -h` for more information on best practices to pass arguments.)

**Comment by pauby** [comment]
Since this doesn't appear to be a Chocolatey issue, rather an issue with using parameters / escaping characters, I've moved this over to a discussion.
