### ISSUE TITLE
System.MissingMethodException when chocolatey.lib is used out of choco.exe

### ISSUE THREAD

**Issue by zbalkan** [chocolatey/choco#2393]
### What You Are Seeing?
I am a user of [BulkCrapUninstaller](https://github.com/Klocman/Bulk-Crap-Uninstaller) and had problems with the amount of time the application wastes while querying Chocolatey package information. I wanted to create an issue on the said project but it turned out there is already an [open ticket](https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/248). The software is called `choco.exe` with required parameters once for the list of packages and then one for each of the packages for detailed information. It is possible to check [the code](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/910d1fe82f656dc2ed0032401176d9739feb85fc/source/UninstallTools/Factory/ChocolateyFactory.cs#L68).
In the said issue, it was suggested to get rid of process creation overhead by running the `choco.exe` once with details and then parse the information. My solution was to utilize `chocolatey.lib` for the requirements.

I created a [new benchmark project](https://github.com/zbalkan/BenchmarkChoco) and did some benchmarks there. It has significant advantages over other methods -**600x faster**. However, when I added the code to the [fork of BulkCrapUninstaller](https://github.com/zbalkan/Bulk-Crap-Uninstaller) and run it, I get the error below:

```
System.MissingMethodException
Method not found: 'Void System.Threading.Mutex.SetAccessControl(System.Security.AccessControl.MutexSecurity)'.
   at chocolatey.infrastructure.synchronization.GlobalMutex.init_mutex()
   at chocolatey.infrastructure.synchronization.GlobalMutex..ctor(Int32 timeOut)
   at chocolatey.infrastructure.synchronization.GlobalMutex.enter[T](Func`1 func, Int32 timeout)
   at chocolatey.Lets.GetChocolatey(Boolean initializeLogging)
   at UninstallTools.Factory.ChocolateyFactory.GetUninstallerEntries(ListGenerationCallback progressCallback) in <path to repos>\Bulk-Crap-Uninstaller\Bulk-Crap-Uninstaller\source\UninstallTools\Factory\ChocolateyFactory.cs:line 32
   at UninstallTools.Factory.ApplicationUninstallerFactory.GetMiscUninstallerEntries(ListGenerationCallback progressCallback) in <path to repos>\Bulk-Crap-Uninstaller\Bulk-Crap-Uninstaller\source\UninstallTools\Factory\ApplicationUninstallerFactory.cs:line 267
```

### What is Expected?
No exception on running the code using the `chocolatey.lib`.

### How Did You Get This To Happen? (Steps to Reproduce)
- Clone the https://github.com/zbalkan/Bulk-Crap-Uninstaller repository.
- Ensure the dependencies are met (BCU-Launcher project is a C++ project that requires the latest MFC v142, others are written C#).
- Build and run the project.

**Comment by zbalkan** [comment]
I'd like to comment on a few stuff before an analysis of the issue:

1. I am aware that the `chocolatey.lib` may not be designed for other applications in mind. So, the issue may not be related to the value created by the chocolatey project.
2. Since it was not designed as an API for 3rd parties, there may be license checks and other controls in place which may affect the use of the library. This may be related and consistent for Chocolatey and ChocolateyGUI, but not 3rd parties.
3. For the same reason, there was no documentation about the library. Although it is easy to get the basics, it became harder to get into the Chocolatey source to find the probable cause when I had this issue.

**Comment by TheCakeIsNaOH** [comment]
I suspect that [this](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/910d1fe82f656dc2ed0032401176d9739feb85fc/source/UninstallTools/UninstallTools.csproj#L3) is your problem. The `UninstallTools` project is running on .Net 5. Chocolatey is built on .Net 4.0
