### ISSUE TITLE
Python alternate source does not handle all keyword

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2540]
### What You Are Seeing?

When running `choco upgrade all` with the `python` alternate source, it tries to install a package named `all` from pypi.

### What is Expected?

That the python alternate source either supports the all keyword for upgrade to upgrade all installed python packages, or throws a not implemented exception.

### How Did You Get This To Happen? (Steps to Reproduce)

`choco upgrade all -s python`

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Chocolatey v0.11.2
Chocolatey is running on Windows v 6.3.9600.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" upgrade all -s python --verbose --debug
Received arguments: upgrade all -s python --verbose --debug
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Checked
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'python' evaluated to a 'python' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='upgrade'|
CacheLocation='C:\Users\Administrator\AppData\Local\Temp\1\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='python'|SourceType='python'|Debug='True'|Verbose='True'|
Trace='False'|Force='False'|Noop='False'|HelpRequested='False'|
UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='all'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='all'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='6.3.9600.0'|
Information.PlatformName='Windows Server 2012 R2'|
Information.ChocolateyVersion='0.11.2.0'|
Information.ChocolateyProductVersion='0.11.2'|
Information.FullName='choco, Version=0.11.2.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='vagrant'|
Information.UserDomainName='WIN-E5K8TM30719'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='False'|Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='C:\Users\Administrator'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='True'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='False'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
Features.ScriptsCheckLastExitCode='False'|
ListCommand.LocalOnly='False'|
ListCommand.IdOnly='False'|ListCommand.IncludeRegistryPrograms='False'|
ListCommand.PageSize='25'|ListCommand.Exact='False'|
ListCommand.ByIdOnly='False'|ListCommand.ByTagOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|
ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
_ Chocolatey:ChocolateyUpgradeCommand - Normal Run Mode _
Upgrading the following packages:
all
By upgrading, you accept licenses for the packages.
Current environment values (may contain sensitive data):
  * 'TMP'='C:\Users\Administrator\AppData\Local\Temp' ('User')
  * 'TEMP'='C:\Users\Administrator\AppData\Local\Temp' ('User')
  * 'ChocolateyLastPathUpdate'='132773512840934131' ('User')
  * 'trigger'='1' ('User')
  * 'FP_NO_HOST_CHECK'='NO' ('Machine')
  * 'USERNAME'='SYSTEM' ('Machine')
  * 'Path'='C:\Python310\Scripts\;C:\Python310\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Syste
m32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\ProgramData\chocolatey\bin;
' ('Machine')
  * 'ComSpec'='C:\Windows\system32\cmd.exe' ('Machine')
  * 'TMP'='C:\Windows\TEMP' ('Machine')
  * 'OS'='Windows_NT' ('Machine')
  * 'windir'='C:\Windows' ('Machine')
  * 'PROCESSOR_ARCHITECTURE'='AMD64' ('Machine')
  * 'TEMP'='C:\Windows\TEMP' ('Machine')
  * 'PATHEXT'='.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW' ('Machine')
  * 'PSModulePath'='C:\Windows\system32\WindowsPowerShell\v1.0\Modules\' ('Machine')
  * 'NUMBER_OF_PROCESSORS'='6' ('Machine')
  * 'PROCESSOR_LEVEL'='6' ('Machine')
  * 'PROCESSOR_IDENTIFIER'='Intel64 Family 6 Model 63 Stepping 2, GenuineIntel' ('Machine')
  * 'PROCESSOR_REVISION'='3f02' ('Machine')
  * 'HOME'='C:\Users\Administrator' ('Machine')
  * 'ChocolateyInstall'='C:\ProgramData\chocolatey' ('Machine')
Calling command ['"C:\Python310\Scripts\pip.exe" -vvv  install --upgrade all']
 [Python] Using pip 21.2.4 from C:\Python310\lib\site-packages\pip (python 3.10)
 [Python] Non-user install because site-packages writeable
 [Python] Created temporary directory: C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\pip-ephem-wheel-cache-1r92
fvdc
 [Python] Created temporary directory: C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\pip-req-tracker-4_wjp547
 [Python] Initialized build tracking at C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\pip-req-tracker-4_wjp547
 [Python] Created build tracker: C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\pip-req-tracker-4_wjp547
 [Python] Entered build tracker: C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\pip-req-tracker-4_wjp547
 [Python] Created temporary directory: C:\Users\Administrator\AppData\Local\Temp\1\chocolatey\pip-install-y957mlq5
 [Python] 1 location(s) to search for versions of all:
 [Python] * https://pypi.org/simple/all/
 [Python] Fetching project page and analyzing links: https://pypi.org/simple/all/
 [Python] Getting page https://pypi.org/simple/all/
 [Python] Found index url https://pypi.org/simple
 [Python] Looking up "https://pypi.org/simple/all/" in the cache
 [Python] Request header has "max_age" as 0, cache bypassed
 [Python] Starting new HTTPS connection (1): pypi.org:443
 [Python] https://pypi.org:443 "GET /simple/all/ HTTP/1.1" 404 13
 [Python] Status code 404 not in (200, 203, 300, 301)
 [Python] Could not fetch URL https://pypi.org/simple/all/: 404 Client Error: Not Found for url: https://pypi.org/simple
/all/ - skipping
[Python] ERROR: Could not find a version that satisfies the requirement all (from versions: none)
[Python] ERROR: No matching distribution found for all
 [Python] Skipping link: not a file: https://pypi.org/simple/all/
 [Python] Given no hashes to check 0 links for project 'all': discarding no candidates
 [Python] Exception information:
[Python] WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
 [Python] Traceback (most recent call last):
[Python] You should consider upgrading via the 'C:\Python310\python.exe -m pip install --upgrade pip' command.
 [Python]   File "C:\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
 [Python]     self._add_to_criteria(self.state.criteria, r, parent=None)
 [Python]   File "C:\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
 [Python]     raise RequirementsConflicted(criterion)
 [Python] pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('all')
 [Python] During handling of the above exception, another exception occurred:
 [Python] Traceback (most recent call last):
 [Python]   File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve
 [Python]     result = self._result = resolver.resolve(
 [Python]   File "C:\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
 [Python]     state = resolution.resolve(requirements, max_rounds=max_rounds)
 [Python]   File "C:\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 343, in resolve
 [Python]     raise ResolutionImpossible(e.criterion.information)
 [Python] pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequiremen
t('all'), parent=None)]
 [Python] The above exception was the direct cause of the following exception:
 [Python] Traceback (most recent call last):
 [Python]   File "C:\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
 [Python]     status = self.run(options, args)
 [Python]   File "C:\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
 [Python]     return func(self, options, args)
 [Python]   File "C:\Python310\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
 [Python]     requirement_set = resolver.resolve(
 [Python]   File "C:\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 103, in resolve
 [Python]     raise error from e
 [Python] pip._internal.exceptions.DistributionNotFound: No matching distribution found for all
 [Python] Removed build tracker: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\1\\chocolatey\\pip-req-tracker-4_wjp54
7'
Command ['"C:\Python310\Scripts\pip.exe" -vvv  install --upgrade all'] exited with '1'

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - all - Could not fetch URL https://pypi.org/simple/all/: 404 Client Error: Not Found for url: https://pypi.org/simple/
all/ - skipping
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 1
~~~

</p>

</details>

**Comment by TheCakeIsNaOH** [comment]
After discussion with @gep13, the all keyword should be not supported on alternate sources, at least for the time being.
