### ISSUE TITLE
Getting error 400 when running choco push in github actions

### ISSUE THREAD

**Issue by raosan** [chocolatey/choco#2625]
### What You Are Seeing?
The remote server returned an error: (400) Bad Request when running `choco push` command from github actions
```
choco push monika.1.6.12.nupkg --source https://push.chocolatey.org/
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Chocolatey v0.12.1
Attempting to push monika.1.[6](https://github.com/raosan/monika/runs/5460809501?check_suite_focus=true#step:11:6).12.nupkg to https://push.chocolatey.org/
Failed to process request. 'Bad Request'. 
The remote server returned an error: (400) Bad Request..
Error: Process completed with exit code 1.
```

### What is Expected?
Should be pushed successfully like when running command in local machine 
```
PS D:\Project\monika\chocolatey> choco push monika.1.6.12.nupkg --source https://push.chocolatey.org/
Chocolatey v0.12.1
Attempting to push monika.1.6.12.nupkg to https://push.chocolatey.org/
monika 1.6.12 was pushed successfully to https://push.chocolatey.org/
```

### How Did You Get This To Happen? (Steps to Reproduce)
by running this command in github actions
```
choco push monika.1.6.12.nupkg --source https://push.chocolatey.org/
```

For detailed info of the package, you can see in my repo here: https://github.com/raosan/monika/tree/v1.6.12/chocolatey

Then see the github actions here: https://github.com/raosan/monika/blob/v1.6.12/.github/workflows/upload-binary.yml

And the complete output of the actions here: https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
choco push monika.1.6.12.nupkg --source https://push.chocolatey.org/ --debug --verbose
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Chocolatey v0.12.1
Chocolatey is running on Windows v 10.0.20[3](https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true#step:11:3)[4](https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true#step:11:4)8.0
Attempting to delete file "C:/ProgramData/Chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\Chocolatey\choco.exe.old".
Command line not shown - sensitive arguments may have been passed.
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
Performing validation checks.
Global Configuration Validation Checks:
 - Package Exit Code / Exit On Reboot = Checked
System State Validation Checks:
 Reboot Requirement Checks:
 - Pending Computer Rename = Checked
 - Pending Component Based Servicing = Checked
 - Pending Windows Auto Update = Checked
 - Pending File Rename Operations = Ignored
 - Pending Windows Package Installer = Checked
 - Pending Windows Package Installer SysWow64 = Checked
The source 'https://push.chocolatey.org/' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple
 check to be sure no sensitive data is shown, especially if copying
 output to a gist for review.
Configuration: CommandName='push'|
CacheLocation='C:\Users\runneradmin\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://push.chocolatey.org/'|SourceType='normal'|
Debug='True'|
Verbose='True'|Trace='False'|Force='False'|Noop='False'|
HelpRequested='False'|UnsuccessfulParsing='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='False'|
AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='monika.1.6.12.nupkg'|
AllVersions='False'|SkipPackageInstallProvider='False'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.20348.0'|
Information.PlatformName='Windows Server 2016'|
Information.ChocolateyVersion='0.12.1.0'|
Information.ChocolateyProductVersion='0.12.1'|
Information.FullName='choco, Version=0.12.1.0, Culture=neutral, PublicKeyToken=79d02ea9cad6[5](https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true#step:11:5)5eb'|

Information.Is[6](https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true#step:11:6)4BitOperatingSystem='True'|
Information.Is64BitProcess='True'|Information.IsInteractive='True'|
Information.UserName='runneradmin'|
Information.UserDomainName='fv-az456-316'|
Information.IsUserAdministrator='True'|
Information.IsUserSystemAccount='False'|
Information.IsUserRemoteDesktop='False'|
Information.IsUserRemote='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
Information.CurrentDirectory='D:\a\monika\monika\chocolatey'|
Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
Features.AllowEmptyChecksums='False'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseEnhancedExitCodes='False'|
Features.UseFipsCompliantChecksums='False'|
Features.ShowNonElevatedWarnings='True'|
Features.ShowDownloadProgress='True'|
Features.StopOnFirstPackageFailure='False'|
Features.UseRememberedArgumentsForUpgrades='False'|
Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
Features.SkipPackageUpgradesWhenNotInstalled='False'|
Features.RemovePackageInformationOnUninstall='False'|
Features.ExitOnRebootDetected='False'|
Features.LogValidationResultsOnWarnings='True'|
Features.UsePackageRepositoryOptimizations='True'|
ListCommand.LocalOnly='False'|ListCommand.IdOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.ByTagOnly='False'|ListCommand.IdStartsWith='False'|
ListCommand.OrderByPopularity='False'|ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|
ListCommand.IncludeVersionOverrides='False'|
UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
UpgradeCommand.ExcludePrerelease='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
SourceCommand.AllowSelfService='False'|
SourceCommand.VisibleToAdminsOnly='False'|
FeatureCommand.Command='unknown'|ConfigCommand.Command='unknown'|
ApiKeyCommand.Remove='False'|PinCommand.Command='unknown'|
OutdatedCommand.IgnorePinned='False'|
ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
TemplateCommand.Command='unknown'|
_ Chocolatey:ChocolateyPushCommand - Normal Run Mode _
Attempting to push monika.1.6.[12](https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true#step:11:12).nupkg to https://push.chocolatey.org/
PUT https://push.chocolatey.org/api/v2/package/
Sending message 'PostRunMessage' out if there are subscribers...
Chocolatey had an error occur:
System.InvalidOperationException: Failed to process request. 'Bad Request'. 
The remote server returned an error: (400) Bad Request.. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   --- End of inner exception stack trace ---
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int[32](https://github.com/raosan/monika/runs/5461163202?check_suite_focus=true#step:11:32) timeout, Boolean disableBuffering)
   at chocolatey.infrastructure.app.nuget.NugetPush.push_package(ChocolateyConfiguration config, String nupkgFilePath)
   at chocolatey.infrastructure.app.services.NugetService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.push_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
Exiting with 1
Error: Process completed with exit code 1.
~~~

</p>

</details>

**Comment by AdmiringWorm** [comment]
I had a quick look at the GitHub workflow that you are using and saw the following location https://github.com/raosan/monika/blob/v1.6.12/.github/workflows/upload-binary.yml#L48 where you are setting the API key to use when pushing the package to the GitHub Token, this won't work and you need to set it to the API Key for your account on community.chocolatey.org.

You can see your api-key on: https://community.chocolatey.org/account (you will need to log in to view the page).

**Comment by raosan** [comment]
You are right. I used wrong secrets. I though wrong API Key [will return 403](https://docs.chocolatey.org/en-us/create/commands/push#troubleshooting)

Thank you for your response @AdmiringWorm . It pushed successfully now

**Comment by AdmiringWorm** [comment]
I am glad you made it work.

The results would have been 403 if it had been a valid CCR API key, unfortunately, the format used by GitHub and CCR is not the same as such it is not detected as a valid API key, and causes the 400 error instead.
