### ISSUE TITLE
Some integration tests are failing when run via Cake script while on Windows

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2759]
### What You Are Seeing?

When running `.\build.ps1 --verbosity=diagnostic --testExecutionType=all` on Windows, quite a few of the integration tests fail, mostly in the integration scenarios. I manually "bisected", and it looks like the tests started failing when #2706 was merged in, which also backed up by the history of workflow runs: https://github.com/chocolatey/choco/actions/workflows/test.yml

However, when running the tests from Visual Studio, they pass, minus the ones already known to be problematic with .Net 4.8 installed (#2690). 

### What is Expected?

That all integration tests pass.

### How Did You Get This To Happen? (Steps to Reproduce)

Run `.\build.ps1 --verbosity=diagnostic --testExecutionType=all` 

Or look at the details of this scheduled test run: https://github.com/chocolatey/choco/runs/7049644165?check_suite_focus=true

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.19044.0
* Windows PowerShell version (Run: `$PSVersionTable`): 5.1.19041.1682
* Chocolatey version (Run `choco --version`): 1.1.0

### Output Log

<details>
<summary>Cake output</summary>

<p>

~~~sh
1) Error : chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors.should_contain_error_output
Should.Core.Exceptions.NotNullException : Assert.NotNull() Failure
   at chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs.when_CommandExecutor_errors.should_contain_error_output() in c:\choco\src\chocolatey.tests.integration\infrastructure\commands\CommandExecutorSpecs.cs:line 73

2) SetUp Failed : chocolatey.tests.integration.scenarios
One or more child tests had errors

Test Run Summary
  Overall result: Failed
  Test Count: 2277, Passed: 1806, Failed: 439, Warnings: 0, Inconclusive: 0, Skipped: 32
    Failed Tests - Failures: 437, Errors: 2, Invalid: 0
    Skipped Tests - Ignored: 32, Explicit: 0, Other: 0
  Start time: 2022-07-07 17:34:47Z
    End time: 2022-07-07 17:46:59Z
    Duration: 731.792 seconds
~~~

</p>

</details>

<details>
<summary>Information about the first failure from TestResults.xml</summary>

<p>

~~~xml

              <test-suite type="TestFixture" id="3-1005" name="CommandExecutorSpecs+when_CommandExecutor_errors" fullname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors" classname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors" runstate="Runnable" testcasecount="3" result="Failed" duration="0.143831" total="3" passed="2" failed="1" inconclusive="0" skipped="0" asserts="0">
                <failure>
                  <message><![CDATA[One or more child tests had errors]]></message>
                </failure>
                <test-case id="3-1007" name="should_contain_error_output" fullname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors.should_contain_error_output" methodname="should_contain_error_output" classname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors" runstate="Runnable" result="Failed" label="Error" duration="0.056967" asserts="0">
                  <failure>
                    <message><![CDATA[Should.Core.Exceptions.NotNullException : Assert.NotNull() Failure]]></message>
                    <stack-trace><![CDATA[   at chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs.when_CommandExecutor_errors.should_contain_error_output() in f:\github\choco\src\chocolatey.tests.integration\infrastructure\commands\CommandExecutorSpecs.cs:line 73]]></stack-trace>
                  </failure>
                </test-case>
                <test-case id="3-1008" name="should_message_the_error" fullname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors.should_message_the_error" methodname="should_message_the_error" classname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors" runstate="Runnable" result="Passed" duration="0.000635" asserts="0" />
                <test-case id="3-1006" name="should_not_return_an_exit_code_of_zero" fullname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors.should_not_return_an_exit_code_of_zero" methodname="should_not_return_an_exit_code_of_zero" classname="chocolatey.tests.integration.infrastructure.commands.CommandExecutorSpecs+when_CommandExecutor_errors" runstate="Runnable" result="Passed" duration="0.001890" asserts="0" />
              </test-suite>
~~~

</p>

</details>

<details>
<summary>Information about the second failure from TestResults.xml</summary>

<p>

~~~xml
            <test-suite type="TestFixture" id="3-1399" name="ListScenarios+when_listing_local_packages" fullname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages" classname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages" runstate="Runnable" testcasecount="4" result="Failed" label="Error" duration="10.005931" total="4" passed="0" failed="4" inconclusive="0" skipped="0" asserts="0" site="Parent">
              <failure>
                <message><![CDATA[SetUp : System.MethodAccessException : [F:\github\choco\code_drop\temp\_PublishedNUnitTests\chocolatey.tests.integration\NuGet.Core.dll] Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.]]></message>
                <stack-trace><![CDATA[   at NuGet.ExpressionRewriter.VisitConstant(ConstantExpression node)
   at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at NuGet.AggregateQuery`1.Rewrite(IQueryable queryable, Expression expression) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateQuery.cs:line 304
   at NuGet.AggregateQuery`1.GetSubQuery(IQueryable queryable, Expression expression) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateQuery.cs:line 259
   at NuGet.AggregateQuery`1.<>c__DisplayClass24_0.<GetSubQueries>b__0(IQueryable`1 query) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateQuery.cs:line 232
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.AggregateQuery`1.GetSubQueries(Expression expression) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateQuery.cs:line 232
   at NuGet.AggregateQuery`1..ctor(IEnumerable`1 queryables, IEqualityComparer`1 equalityComparer, ILogger logger, Boolean ignoreFailures) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateQuery.cs:line 30
   at NuGet.AggregateRepository.CreateAggregateQuery(IEnumerable`1 queries) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateRepository.cs:line 216
   at NuGet.AggregateRepository.Search(String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\AggregateRepository.cs:line 186
   at NuGet.PackageRepositoryExtensions.Search(IPackageRepository repository, String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\PackageRepositoryExtensions.cs:line 302
   at NuGet.PackageRepositoryExtensions.Search(IPackageRepository repository, String searchTerm, Boolean allowPrereleaseVersions) in C:\github_local\organisations\chocolatey\nuget-chocolatey\src\Core\Repositories\PackageRepositoryExtensions.cs:line 289
   at chocolatey.infrastructure.app.nuget.NugetList.execute_package_search(ChocolateyConfiguration configuration, ILogger nugetLogger) in f:\github\choco\src\chocolatey\infrastructure.app\nuget\NugetList.cs:line 67
   at chocolatey.infrastructure.app.nuget.NugetList.GetPackages(ChocolateyConfiguration configuration, ILogger nugetLogger) in f:\github\choco\src\chocolatey\infrastructure.app\nuget\NugetList.cs:line 33
   at chocolatey.infrastructure.app.services.NugetService.<list_run>d__15.MoveNext() in f:\github\choco\src\chocolatey\infrastructure.app\services\NugetService.cs:line 130
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.<list_run>d__17.MoveNext() in f:\github\choco\src\chocolatey\infrastructure.app\services\ChocolateyPackageService.cs:line 181
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at chocolatey.tests.integration.scenarios.ListScenarios.when_listing_local_packages.Because() in f:\github\choco\src\chocolatey.tests.integration\scenarios\ListScenarios.cs:line 258
   at chocolatey.tests.TinySpec.Setup() in f:\github\choco\src\chocolatey.tests\TinySpec.cs:line 71]]></stack-trace>
              </failure>
              <test-case id="3-1402" name="should_contain_a_summary" fullname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages.should_contain_a_summary" methodname="should_contain_a_summary" classname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages" runstate="Runnable" result="Failed" duration="0.000000" asserts="0">
                <failure>
                  <message><![CDATA[TestFixtureSetUp failed in when_listing_local_packages]]></message>
                </failure>
              </test-case>
              <test-case id="3-1403" name="should_contain_debugging_messages" fullname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages.should_contain_debugging_messages" methodname="should_contain_debugging_messages" classname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages" runstate="Runnable" result="Failed" duration="0.000000" asserts="0">
                <failure>
                  <message><![CDATA[TestFixtureSetUp failed in when_listing_local_packages]]></message>
                </failure>
              </test-case>
              <test-case id="3-1400" name="should_contain_packages_and_versions_with_a_space_between_them" fullname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages.should_contain_packages_and_versions_with_a_space_between_them" methodname="should_contain_packages_and_versions_with_a_space_between_them" classname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages" runstate="Runnable" result="Failed" duration="0.000000" asserts="0">
                <failure>
                  <message><![CDATA[TestFixtureSetUp failed in when_listing_local_packages]]></message>
                </failure>
              </test-case>
              <test-case id="3-1401" name="should_not_contain_packages_and_versions_with_a_pipe_between_them" fullname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages.should_not_contain_packages_and_versions_with_a_pipe_between_them" methodname="should_not_contain_packages_and_versions_with_a_pipe_between_them" classname="chocolatey.tests.integration.scenarios.ListScenarios+when_listing_local_packages" runstate="Runnable" result="Failed" duration="0.000000" asserts="0">
                <failure>
                  <message><![CDATA[TestFixtureSetUp failed in when_listing_local_packages]]></message>
                </failure>
              </test-case>
            </test-suite>
~~~

</p>

</details>

**Comment by TheCakeIsNaOH** [comment]
Fixed via https://github.com/chocolatey/choco/commit/2864c01d72bd2fda1fa6833acdfcea2e51be16f5
