### ISSUE TITLE
Specified argument was out of the range of valid values. Parameter name: zipFileName.

### ISSUE THREAD

**Issue by Josh68** [chocolatey/choco#2820]
Suddenly today, running `choco upgrade all -y` fails on every package upgrade with this error (no package downloaded, either)
```
Specified argument was out of the range of valid values. Parameter name: zipFileName.
```

Every command run in Admin-elevated prompt. I tried both Powershell and CMD, within Terminal, which is what I usually use.

I found if I closed everything, started a new Admin Terminal/CMD and upgraded specific packages, the upgrades would succeed.

One by one, I upgraded all out-of-date packages.

Still, now if I run `choco upgrade all -y`, I get `Chocolatey upgraded 0/0 packages.`, but it's followed by the same error. Here's the verbose dump from the end of my log.

```
Chocolatey upgraded 0/0 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2022-09-18 08:59:47,532 11756 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2022-09-18 08:59:47,532 11756 [ERROR] - Specified argument was out of the range of valid values.
Parameter name: zipFileName
2022-09-18 08:59:47,541 11756 [ERROR] - More Details: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: zipFileName
   at MS.Internal.IO.Zip.ZipIOBlockManager.ValidateNormalizeFileName(String zipFileName)
   at MS.Internal.IO.Zip.ZipIOLocalFileHeader.ParseRecord(BinaryReader reader, Encoding encoding)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.ParseRecord(BinaryReader reader, String fileName, Int64 position, ZipIOCentralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.SeekableLoad(ZipIOBlockManager blockManager, String fileName)
   at MS.Internal.IO.Zip.ZipIOBlockManager.LoadLocalFileBlock(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFile(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<GetPackages>d__28.MoveNext()
   at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
   at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Boolean performAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.upgrade_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2022-09-18 08:59:47,541 11756 [DEBUG] - Exiting with 1
```

Any idea what my issue may be? Thanks

-----

Note: The only thing I could think of to try to fix any problems with chocolatey itself was a forced upgrade (replaced the same version I already had). This didn't change anything.

**Comment by vexx32** [comment]
Thanks for the report! That looks like an odd one. Could you add the missing items from our [issue template](https://github.com/chocolatey/choco/issues/new?assignees=&labels=&template=zReportIssue.md) and fill them in so we can have a more complete picture of what's going on?

It would also be good if we could get a list of the packages you have installed, if that's possible?

**Comment by Josh68** [comment]
Sorry, I had given up and reinstalled Chocolatey and all of my apps. No longer able to provide any more useful logs.
