### ISSUE TITLE
Receive Error When trying to Upgrade 2 or More packages in One Command

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco#2895]
### What You Are Seeing?
When running a choco upgrade command specifying more than one package I receive the following error. 
No backup has been created before trying to reset the current configuration, and removal of the backup was not requested.

### What is Expected?
This should just upgrade the packages I define in the command with no error.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Have Chocolatey V 1.2.0 installed
1. Run a `choco upgrade googlechrome putty -y`
1. You'll receive the following error: `No backup has been created before trying to reset the current configuration, and removal of the backup was not requested.`

Tested this running choco V 1.1.0 and works as expected.
### System Details

* OS Build: 10.0.19045.0
* Windows PowerShell version: 5.1.19041.1682
* Chocolatey version: 1.2.0

### Output Log

<details>
<summary>Relevant Part of Chocolatey Log</summary>

<p>

~~~sh
2022-11-09 10:51:29,771 6960 [ERROR] - No backup has been created before trying to reset the current configuration, and removal of the backup was not requested.
2022-11-09 10:51:29,771 6960 [ERROR] - More Details: System.InvalidOperationException: No backup has been created before trying to reset the current configuration, and removal of the backup was not requested.
   at chocolatey.infrastructure.app.configuration.ChocolateyConfiguration.reset_config(Boolean removeBackup)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Boolean performAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.NugetService.upgrade_run(ChocolateyConfiguration config, Action`1 continueAction, Action`1 beforeUpgradeAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_function[T](ChocolateyConfiguration config, Func`2 function)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.upgrade_run(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2022-11-09 10:51:29,771 6960 [DEBUG] - Exiting with 1
~~~

</p>

</details>

### References
- [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/15765)

**Comment by TheCakeIsNaOH** [comment]
@ryanrichter94 probable duplicate of #2884?

**Comment by ryanrichter94** [comment]
@TheCakeIsNaOH It is, sorry about that.
