### ISSUE TITLE
Can't choco install a package from the filesystem

### ISSUE THREAD

**Issue by nex3** [chocolatey/choco#3216]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

I maintain [`dart_cli_pkg`](https://github.com/google/dart_cli_pkg), a tool for Dart projects that assists in releasing them across many different platforms, including Chocolatey. Among our automated tests are several integration tests that ensure Chocolatey can properly install and run the packages we generate. These have _mostly_ worked well, but recently they've begun to fail flakily with [messages like this](https://github.com/google/dart_cli_pkg/actions/runs/5273143429/jobs/9536412453?pr=132):

```shellsession
$ choco install --ignore-dependencies C:\Users\runneradmin\AppData\Local\Temp\dart_test_b9117bf0\my_app/build/my_app_choco.1.2.3-beta.nupkg
Chocolatey v2.0.0
Package name cannot be a path to a file on a remote, or local file system.

To install a local, or remote file, you may use:
  choco install my_app_choco --version="1.2.3-beta" --prerelease --source="C:\Users\runneradmin\AppData\Local\Temp\dart_test_b9117bf0\my_app\build"
```

Despite the message, this failure doesn't seem to be consistent; re-running the build often fixes it. However, in https://github.com/google/dart_cli_pkg/pull/133 I attempted to update the tests to use the format suggested by the error message, and instead got a different error:

```shellsession
$ choco install my_app_choco --ignore-dependencies --source=C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app/build/my_app_choco.1.2.3.nupkg
Chocolatey v2.0.0
Installing the following packages:
my_app_choco
By installing, you accept licenses for the packages.
Unable to connect to source 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app/build/my_app_choco.1.2.3.nupkg':
 The path 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app/build/my_app_choco.1.2.3.nupkg' for the selected source could not be resolved.
my_app_choco not installed. The package was not found with the source(s) listed.
 Source(s): 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app\build'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - my_app_choco - my_app_choco not installed. The package was not found with the source(s) listed.
 Source(s): 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app\build'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.
```

### What is Expected?

I would expect `choco install my_app_choco --source=C:\path\to\my_app_choco.1.2.3.nupkg` to successfully install the package.

### How Did You Get This To Happen?

1. My tests ran `choco pack --yes build/chocolatey/my_app_choco.nuspec --out=build`
2. My tests ran `choco install my_app_choco --ignore-dependencies --source=C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app/build/my_app_choco.1.2.3.nupkg`

### System Details

* Operating System: Microsoft Windows Server 2022 10.0.20348
* Windows PowerShell version: whatever the default is for GitHub Actions
* Chocolatey CLI Version: 2.0.0
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator: GitHub Actions

### Installed Packages

```bash
N/A, only custom test packages were installed
```

### Output Log

```bash
Chocolatey v2.0.0
    Chocolatey is running on Windows v 10.0.20348.0
    Attempting to delete file "C:/ProgramData/Chocolatey/choco.exe.old".
    Attempting to delete file "C:\ProgramData\Chocolatey\choco.exe.old".
    Command line: "C:\ProgramData\Chocolatey\choco.exe" install my_app_choco --debug --verbose --ignore-dependencies --source=C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app/build/my_app_choco.1.2.3-beta.nupkg
    Received arguments: install my_app_choco --debug --verbose --ignore-dependencies --source=C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app/build/my_app_choco.1.2.3-beta.nupkg
    RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
    Sending message 'PreRunMessage' out if there are subscribers...
    [Pending] Removing all pending packages that should not be considered installed...
    Performing validation checks.
    Global Configuration Validation Checks:
     - Package Exit Code / Exit On Reboot = Checked
    System State Validation Checks:
     Reboot Requirement Checks:
     - Pending Computer Rename = Checked
     - Pending Component Based Servicing = Checked
     - Pending Windows Auto Update = Checked
     - Pending File Rename Operations = Ignored
     - Pending Windows Package Installer = Checked
     - Pending Windows Package Installer SysWow64 = Checked
    The source 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app/build/my_app_choco.1.2.3-beta.nupkg' evaluated to a 'normal' source type
    
    NOTE: Hiding sensitive configuration data! Please double and triple
     check to be sure no sensitive data is shown, especially if copying
     output to a gist for review.
    Configuration: CommandName='install'|
    CacheLocation='C:\Users\runneradmin\AppData\Local\Temp\chocolatey'|
    CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
    Sources='C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app/build/my_app_choco.1.2.3-beta.nupkg'|
    
    SourceType='normal'|ShowOnlineHelp='False'|Debug='True'|Verbose='True'|
    Trace='False'|Force='False'|Noop='False'|HelpRequested='False'|
    UnsuccessfulParsing='False'|RegularOutput='True'|QuietOutput='False'|
    PromptForConfirmation='False'|DisableCompatibilityChecks='False'|
    AcceptLicense='False'|AllowUnofficialBuild='False'|
    Input='my_app_choco'|
    AllVersions='False'|SkipPackageInstallProvider='False'|
    SkipHookScripts='False'|PackageNames='my_app_choco'|Prerelease='False'|
    ForceX86='False'|OverrideArguments='False'|NotSilent='False'|
    ApplyPackageParametersToDependencies='False'|
    ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='True'|
    AllowDowngrade='False'|ForceDependencies='False'|PinPackage='False'|
    Information.PlatformType='Windows'|
    Information.PlatformVersion='10.0.20348.0'|
    Information.PlatformName='Windows Server 2016'|
    Information.ChocolateyVersion='2.0.0.0'|
    Information.ChocolateyProductVersion='2.0.0'|
    Information.FullName='choco, Version=2.0.0.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|
    
    Information.Is64BitOperatingSystem='True'|
    Information.Is64BitProcess='True'|Information.IsInteractive='True'|
    Information.UserName='runneradmin'|
    Information.UserDomainName='fv-az435-413'|
    Information.IsUserAdministrator='True'|
    Information.IsUserSystemAccount='False'|
    Information.IsUserRemoteDesktop='False'|
    Information.IsUserRemote='True'|
    Information.IsProcessElevated='True'|
    Information.IsLicensedVersion='False'|Information.LicenseType='Foss'|
    Information.CurrentDirectory='D:\a\dart_cli_pkg\dart_cli_pkg'|
    Features.AutoUninstaller='True'|Features.ChecksumFiles='True'|
    Features.AllowEmptyChecksums='False'|
    Features.AllowEmptyChecksumsSecure='True'|
    Features.FailOnAutoUninstaller='False'|
    Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
    Features.LogEnvironmentValues='False'|Features.LogWithoutColor='False'|
    Features.VirusCheck='False'|
    Features.FailOnInvalidOrMissingLicense='False'|
    Features.IgnoreInvalidOptionsSwitches='True'|
    Features.UsePackageExitCodes='True'|
    Features.UseEnhancedExitCodes='False'|
    Features.UseFipsCompliantChecksums='False'|
    Features.ShowNonElevatedWarnings='True'|
    Features.ShowDownloadProgress='True'|
    Features.StopOnFirstPackageFailure='False'|
    Features.UseRememberedArgumentsForUpgrades='False'|
    Features.IgnoreUnfoundPackagesOnUpgradeOutdated='False'|
    Features.SkipPackageUpgradesWhenNotInstalled='False'|
    Features.RemovePackageInformationOnUninstall='False'|
    Features.ExitOnRebootDetected='False'|
    Features.LogValidationResultsOnWarnings='True'|
    Features.UsePackageRepositoryOptimizations='True'|
    ListCommand.LocalOnly='False'|ListCommand.IdOnly='False'|
    ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
    ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
    ListCommand.ByTagOnly='False'|ListCommand.IdStartsWith='False'|
    ListCommand.OrderByPopularity='False'|ListCommand.ApprovedOnly='False'|
    ListCommand.DownloadCacheAvailable='False'|
    ListCommand.NotBroken='False'|
    ListCommand.IncludeVersionOverrides='False'|
    ListCommand.ExplicitPageSize='False'|
    ListCommand.ExplicitSource='False'|
    UpgradeCommand.FailOnUnfound='False'|
    UpgradeCommand.FailOnNotInstalled='False'|
    UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
    UpgradeCommand.ExcludePrerelease='False'|
    NewCommand.AutomaticPackage='False'|
    NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
    SourceCommand.Priority='0'|SourceCommand.BypassProxy='False'|
    SourceCommand.AllowSelfService='False'|
    SourceCommand.VisibleToAdminsOnly='False'|
    FeatureCommand.Command='unknown'|ConfigCommand.Command='Unknown'|
    ApiKeyCommand.Command='Unknown'|PinCommand.Command='Unknown'|
    OutdatedCommand.IgnorePinned='False'|
    ExportCommand.IncludeVersionNumbers='False'|Proxy.BypassOnLocal='True'|
    TemplateCommand.Command='unknown'|
    _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
    Installing the following packages:
    my_app_choco
    By installing, you accept licenses for the packages.
    Running list with the following filter = ''
    --- Start of List ---
    Resolving resource PackageSearchResource for source C:\ProgramData\chocolatey\lib
    7zip.install 22.1.0
    ant 1.10.13
    apache-httpd 2.4.55
    aria2 1.36.0
    awscli 2.11.25
    azcopy10 10.19.0
    bazel 6.2.1
    bicep 0.17.1
    chocolatey 2.0.0
    chocolatey-compatibility.extension 1.0.0
    chocolatey-core.extension 1.4.0
    chocolatey-windowsupdate.extension 1.0.5
    cmake.install 3.26.4
    composer 6.3.0
    docker-compose 1.29.2
    DotNet3.5 3.5.201[60](https://github.com/google/dart_cli_pkg/actions/runs/5273586456/jobs/9537187587#step:9:61)716
    gradle 8.1.1
    hg 5.0.0
    hub 2.14.2
    imagemagick 7.1.1.1100
    imagemagick.app 7.1.1.1100
    InnoSetup 6.2.2
    jq 1.6.0
    julia 1.9.0
    KB2919355 1.0.20160915
    KB2919442 1.0.20160915
    KB2999226 1.0.20181019
    KB3033929 1.0.5
    KB3035131 1.0.3
    kubernetes-cli 1.27.2
    kubernetes-helm 3.11.3
    llvm 15.0.7
    maven 3.8.7
    mingw 11.2.0.7112021
    Minikube 1.30.1
    mongodb 5.0.15
    mongodb.install 5.0.15
    nginx 1.25.0
    nodejs 18.16.0
    nodejs.install 18.16.0
    nssm 2.24.101.20180116
    nuget.commandline 6.6.0
    packer 1.8.7
    php 8.2.6
    pulumi 3.69.0
    R.Project 4.3.0
    rtools 4.3.5550
    sbt 1.9.0
    strawberryperl 5.32.1.1
    swig 4.1.1
    tortoisesvn 1.14.5.294[65](https://github.com/google/dart_cli_pkg/actions/runs/5273586456/jobs/9537187587#step:9:66)
    vcredist140 14.36.32532
    vswhere 3.1.4
    wixtoolset 3.11.2
    --- End of List ---
    Resolving resource ListResource for source C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b[81](https://github.com/google/dart_cli_pkg/actions/runs/5273586456/jobs/9537187587#step:9:82)6d\my_app/build/my_app_choco.1.2.3-beta.nupkg
    Unable to connect to source 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app/build/my_app_choco.1.2.3-beta.nupkg':
     System.InvalidOperationException: The path 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app/build/my_app_choco.1.2.3-beta.nupkg' for the selected source could not be resolved.
       at NuGet.Protocol.LocalPackageSearchResource.<>c__DisplayClass2_0.<SearchAsync>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.LocalPackageSearchResource.<SearchAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Protocol.LocalPackageListResource.<PackageAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at chocolatey.infrastructure.app.nuget.NugetList.<>c__DisplayClass18_1.<FindPackage>b__1()
       at chocolatey.infrastructure.tolerance.FaultTolerance.TryCatchWithLoggingException[T](Func`1 function, String errorMessage, Boolean throwError, Boolean logWarningInsteadOfError, Boolean logDebugInsteadOfError, Boolean isSilent)
    my_app_choco not installed. The package was not found with the source(s) listed.
     Source(s): 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app\build'
     NOTE: When you specify explicit sources, it overrides default sources.
    If the package version is a prerelease and you didn't specify `--pre`,
     the package may not be found.
    Please see https://docs.chocolatey.org/en-us/troubleshooting for more
     assistance.
    
    Chocolatey installed 0/1 packages. 1 packages failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    
    Failures
     - my_app_choco - my_app_choco not installed. The package was not found with the source(s) listed.
     Source(s): 'C:\Users\runneradmin\AppData\Local\Temp\dart_test_4d3b816d\my_app\build'
     NOTE: When you specify explicit sources, it overrides default sources.
    If the package version is a prerelease and you didn't specify `--pre`,
     the package may not be found.
    Please see https://docs.chocolatey.org/en-us/troubleshooting for more
     assistance.
    Sending message 'PostRunMessage' out if there are subscribers...
    Exiting with 1
```

**Comment by TheCakeIsNaOH** [comment]
As per https://docs.chocolatey.org/en-us/choco/release-notes#may-31-2023 and https://github.com/chocolatey/choco/issues/3008 , the ability to install a package using a path to a `.nupkg` was removed in Chocolatey CLI v2.0.0 

> These have mostly worked well, but recently they've begun to fail flakily

This potentially could be caused by some runners having Chocolatey CLI upgraded to v2.0.0 and some having an older version.

>  attempted to update the tests to use the format suggested by the error message, and instead got a different error:

The message states to use 
`--source="C:\Users\runneradmin\AppData\Local\Temp\dart_test_b9117bf0\my_app\build"`
not 
`--source=C:\Users\runneradmin\AppData\Local\Temp\dart_test_7a818fe8\my_app/build/my_app_choco.1.2.3.nupkg`


So the correct source is the folder that the `.nupkg` is in, not the path to the `.nupkg` itself. Therefore, use `choco install my_app_choco --source=C:\path\to\folder\that\nupkg\is\in`
