### ISSUE TITLE
Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

### ISSUE THREAD

**Issue by TheBigBear** [chocolatey/choco#3228]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

When I try to run ```choco`` or ```choco --version``` or ```choco list``` after I upgraded from chocolatey 1.40 to 2.0.0 chocolatey does not see to start up at all. All I get is a single line of output saying: 
```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```
I will include the .NET framework install-info from that Windows server 2016 install. 

[choco.summary.log](https://github.com/chocolatey/choco/files/11859366/choco.summary.log)

[chocolatey.log](https://github.com/chocolatey/choco/files/11859369/chocolatey.log)

[asoftreport.txt](https://github.com/chocolatey/choco/files/11859362/asoftreport.txt)

[dotnetversions.txt](https://github.com/chocolatey/choco/files/11859364/dotnetversions.txt)

### What is Expected?

I expect chocolatey to start up and give me the helpscreen or the version number or the list of installed packages. But instead I get a single line saying:
```
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

### How Did You Get This To Happen?

I ran all of these cmds
choco
choco --version
choco list

### System Details

* Operating System: 10.0.14393.0
* Windows PowerShell version:  5.1.14393.5582
* Chocolatey CLI Version: only gives above error
* Chocolatey Licensed Extension version: only gives above error
* Chocolatey License type: no license purchased - free edition
* Terminal/Emulator: windows powershell

### Installed Packages

```bash
can't show installed packages as it errors out
```

### Output Log

```bash
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```
```


### Additional Context

_No response_

**Comment by gep13** [comment]
@TheBigBear apologies on not getting back you to sooner about this!

Can I ask if you are still seeing this same problem?

This is a new one on me, as I don't think I have seen this problem before.

In the issue you created, you said the following:

> Chocolatey Licensed Extension version: only gives above error

Just to confirm... Do you have the `chocolatey.extension` package installed at all?  i.e. are you a paying customer of Chocolatey Software, for example with a Pro, or Business license?

I assume that everything was working correctly, prior to the upgrade to 2.0.0?

On your system, do you have any virus, or malware, software, that complete be interfering with the operation of Chocolatey?

On the file system, so you have anything in the `C:\ProgramData\chocolatey\extensions` folder?  Is so, what do you have in there?

**Comment by TheBigBear** [comment]
@gep13 Hi Gary, no I am not a licensed user, sorry to have confused you. 
Yes, everything was working just fine up to the attempt to upgrade to version 2.0.0
This is one of a few server 2016 servers we have but the only one where it fails to run at all. 
The one and only AV on it is MS defender is enabled. 
And no, I have no extensions folder anymore, remember I had removed everything using the provided ps script. 
And if I remove ```C:\ProgramData\chocolatey\``` and re-install now, the install looks ok, it finishes without errror, but on trying to start any choco cmd I get the dreaded errro above. 

And I checked in my backups on the earlier version 1.4.0 I did have a extensions folder with 4 subfolders
```chocolatey-compatibility```
```chocolatey-core```
```chocolatey-dotnetfx```
```chocolatey-windowsupdate```

**Comment by Bzly** [comment]
I'm seeing this on a fresh install of chocolatey; I have just copied the PS install code from the install page. 

As described above the install looks to complete successfully, I restart my shell and choco throws the error.

My chocolatey.log spits out the following per call of `choco`:

```
2023-07-31 18:34:51,854 13792 [DEBUG] - XmlConfiguration is now operational
2023-07-31 18:34:51,931 13792 [DEBUG] - Adding new type 'CygwinService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,933 13792 [DEBUG] - Adding new type 'CygwinService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,934 13792 [DEBUG] - Adding new type 'PythonService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,934 13792 [DEBUG] - Adding new type 'PythonService' for type 'IListSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,935 13792 [DEBUG] - Adding new type 'PythonService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,935 13792 [DEBUG] - Adding new type 'PythonService' for type 'IUninstallSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,937 13792 [DEBUG] - Adding new type 'RubyGemsService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,937 13792 [DEBUG] - Adding new type 'RubyGemsService' for type 'IListSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,938 13792 [DEBUG] - Adding new type 'RubyGemsService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-07-31 18:34:51,939 13792 [DEBUG] - Adding new type 'SystemStateValidation' for type 'IValidation' from assembly 'choco'
2023-07-31 18:34:51,940 13792 [DEBUG] - Adding new type 'CacheFolderLockdownValidation' for type 'IValidation' from assembly 'choco'
2023-07-31 18:34:52,459 13792 [ERROR] - Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
2023-07-31 18:34:52,475 13792 [ERROR] - More Details: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at chocolatey.infrastructure.app.registration.ChocolateyRegistrationModule.RegisterDependencies(IContainerRegistrator registrator, ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.registration.ContainerBinding.RegisterComponents(Container container)
   at chocolatey.infrastructure.registration.SimpleInjectorContainer.Initialize()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at chocolatey.console.Program.Main(String[] args)
2023-07-31 18:34:52,477 13792 [DEBUG] - Exiting with 1
```

It's not critical on this machine, so I will leave it in this state for troubleshooting attempts.

**Comment by pauby** [comment]
@Bzly So we can gather all the information we need, can you raise a new issue?

**Comment by gabienache** [comment]
I've just ran into the same issue on a fresh installation, only to realize that there was no problem with the installation, but rather the system needed a restart. After restart choco runs with no problems.

**Comment by CalebBrendel** [comment]
Confirming that a reboot resolved this for me as well. Note: This took unusually long to install compared to prior sites I have installed for clients. I believe they have a poor internet connection and that could be a result of it or the system make be slow. Definitely suggest a reboot before re-installing. Thanks!

**Comment by chambersmp** [comment]
This error appears to be resolved through (re)installation of .Net Framework. 

This is a prerequisites for choco cli:
* PowerShell v2+ (minimum is v3 for install from this website due to [TLS 1.2 requirement](https://chocolatey.org/blog/remove-support-for-old-tls-versions))
* .NET Framework 4.8 (the installation will attempt to install .NET 4.8 if you do not have it installed)

In the particular instance, .NET Framework had been removed from the impacted system and presented these `choco` command errors.

Reinstalling chocolatey cli will also attempt reinstall .Net Framework 4.8 as described in the https://chocolatey.org/install#install-step2. A reboot will ensure all necessary files are updated and potential conflicts with existing applications are resolved.

**Comment by corbob** [comment]
I think @chambersmp is correct in that a reinstallation of .Net Framework solves it. I was able to accidentally cause this issue when trying to force a .Net installation by mucking with the registry. From what I can tell, there is a registry key (`HKLM:\software\microsoft\NET Framework Setup\NDP\v4\Full\`) that has a DWORD Property `Release`. If this property is too low, then this error occurs. If this property on the other hand doesn't exist, then it works just fine. Now, it's not easy to adjust this property. I can do it because I took ownership from `TrustedInstaller`. I highly recommend that you do **NOT** do the same. If you encounter this error, you should attempt reinstalling .Net through the official installer with one or more reboots if necessary.

<img width="921" height="402" alt="Image" src="https://github.com/user-attachments/assets/a10a701b-bde5-4725-9ae3-12918a746613" />

@TheBigBear I realize this issue is rather old, but if you're still encountering the issue, could you check the above registry key and attempt reinstalling .Net Framework?

**Comment by corbob** [comment]
While I believe this is an environment issue, I also found where I think this is happening (or at least relatively close), and I think we can do the check for .Net 4.8 prior to that point and thus give a more appropriate error.
