### ISSUE TITLE
'[ERROR] - Unable to load one or more of the requested types.' on calling choco after fresh install

### ISSUE THREAD

**Issue by bzly** [chocolatey/choco#3289]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

```
PowerShell 7.3.6
PS C:\Users\jbdud> choco --version
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

### What is Expected?

The installed choco version number.

### How Did You Get This To Happen?

1. Opened a PS 7.3.6 shell in Microsoft Terminal running as Administrator
2. Copied the Powershell command presented on https://chocolatey.org/install
3. The install completed without error
4. Restarted Microsoft Terminal
5. Enter any choco command

### System Details

* Operating System: 10.0.19045.0
* Windows PowerShell version: 7.3.6
* Chocolatey CLI Version: `choco --version` returns error above. Given new install, presumably 2.2.0.
* Chocolatey Licensed Extension version: unknown
* Chocolatey License type: no license/free license
* Terminal/Emulator: Microsoft Terminal

### Installed Packages

```bash
N/A
```

### Output Log

```bash
2023-07-31 21:49:15,076 13924 [DEBUG] - XmlConfiguration is now operational
2023-07-31 21:49:15,114 13924 [DEBUG] - Adding new type 'CygwinService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,115 13924 [DEBUG] - Adding new type 'CygwinService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,116 13924 [DEBUG] - Adding new type 'PythonService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,116 13924 [DEBUG] - Adding new type 'PythonService' for type 'IListSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,117 13924 [DEBUG] - Adding new type 'PythonService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,117 13924 [DEBUG] - Adding new type 'PythonService' for type 'IUninstallSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,118 13924 [DEBUG] - Adding new type 'RubyGemsService' for type 'IAlternativeSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,118 13924 [DEBUG] - Adding new type 'RubyGemsService' for type 'IListSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,119 13924 [DEBUG] - Adding new type 'RubyGemsService' for type 'IInstallSourceRunner' from assembly 'choco'
2023-07-31 21:49:15,119 13924 [DEBUG] - Adding new type 'SystemStateValidation' for type 'IValidation' from assembly 'choco'
2023-07-31 21:49:15,120 13924 [DEBUG] - Adding new type 'CacheFolderLockdownValidation' for type 'IValidation' from assembly 'choco'
2023-07-31 21:49:15,439 13924 [ERROR] - Chocolatey had an error occur:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at chocolatey.infrastructure.app.registration.ChocolateyRegistrationModule.RegisterDependencies(IContainerRegistrator registrator, ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.registration.ContainerBinding.RegisterComponents(Container container)
   at chocolatey.infrastructure.registration.SimpleInjectorContainer.Initialize()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at chocolatey.console.Program.Main(String[] args)
2023-07-31 21:49:15,441 13924 [DEBUG] - Exiting with 1
```

### Additional Context

.NET versions, updates etc listed here: https://gist.github.com/Bzly/d8cfbd379e215566d40ba595978fa2b0

Possibly linked to #3228

**Comment by nfortnowTandon** [comment]
I am also running into this error when trying to run choco on my windows 10 vm -- any updates?

**Comment by vexx32** [comment]
I brought up a fresh Win10 VM to try to test this out and I cannot reproduce at least on the current latest PowerShell and Chocolatey CLI versions (7.5.3 and 2.5.1, respectively).

Can y'all check if it's still an issue? This feels like it's an environmental thing *somewhere* but I'm really unsure where the issue would arise from.

**Comment by corbob** [comment]
I was just able to accidentally reproduce the issue [here](https://github.com/chocolatey/choco/issues/3228#issuecomment-3300138542). Based on that, it feels like a broken .Net installation.

**Comment by corbob** [comment]
I'm as confident as I can be that this is an environment issue that can be resolved by reinstalling .Net Framework. As such, I'll close this issue. If this is incorrect, we can always reopen the issue.
