### ISSUE TITLE
Chocolatey v2.3.0 || Failed to fetch results from V2 feed

### ISSUE THREAD

**Issue by gurupreet18121990** [chocolatey/choco#3485]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Issue:  Chocolatey  is unable to install "aws cli" 
While trying to install the "aws cli" using the chocolatey, it gives the error, which indicates that the source package is not available, also I tried with the "--pre" option but no luck . 

While I tried to install other packages like "7zip" or "notepad++" that works fine. 
choco install 7zip -y
choco install notepadplusplus -y

### What is Expected?

It's not installing the aws-cli package. 

### How Did You Get This To Happen?

1. I ran the command "choco install awscli"
2. I tried with the "--pre" option  "choco install awscli --pre " 

### System Details

* Operating System:  windows 2016
* Chocolatey CLI Version: v2.3.0

### Installed Packages

```bash
I can install the package locally by using the following command. 

curl -O https://awscli.amazonaws.com/AWSCLIV2.msi

msiexec.exe /i AWSCLIV2.msi /quiet
```

### Output Log

```bash
PS C:\temp> choco install awscli
Chocolatey v2.3.0
Installing the following packages:
awscli
By installing, you accept licenses for the packages.
awscli not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - awscli - awscli not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://docs.chocolatey.org/en-us/troubleshooting for more
 assistance.

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip-top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare

Below error, I got in the log file. 
024-07-15 18:06:45,273 5788 [DEBUG] - _ Chocolatey:ChocolateySearchCommand - Normal Run Mode _
2024-07-15 18:06:45,273 5788 [DEBUG] - Searching for package information
2024-07-15 18:06:45,288 5788 [DEBUG] - Running list with the following filter = 'awscli'
2024-07-15 18:06:45,288 5788 [DEBUG] - --- Start of List ---
2024-07-15 18:06:45,445 5788 [DEBUG] - Resolving resource PackageSearchResource for source https://community.chocolatey.org/api/v2/
2024-07-15 18:06:45,788 5788 [INFO ] - [NuGet]   CACHE https://community.chocolatey.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='awscli'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
2024-07-15 18:06:45,820 5788 [INFO ] - [NuGet]   GET http://community.chocolatey.org/api/v2/Search?searchTerm='awscli'&targetFramework=''&includePrerelease=false&$filter=IsLatestVersion&$orderby=Id&$top=30&$skiptoken='forge'
2024-07-15 18:07:15,835 5788 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2024-07-15 18:07:15,851 5788 [ERROR] - Failed to fetch results from V2 feed at 'http://community.chocolatey.org/api/v2/Search?searchTerm='awscli'&targetFramework=''&includePrerelease=false&$filter=IsLatestVersion&$orderby=Id&$top=30&$skiptoken='forge'' with following message : An error occurred while sending the request.
2024-07-15 18:07:15,851 5788 [ERROR] - More Details: NuGet.Protocol.Core.Types.FatalProtocolException: Failed to fetch results from V2 feed at 'http://community.chocolatey.org/api/v2/Search?searchTerm='awscli'&targetFramework=''&includePrerelease=false&$filter=IsLatestVersion&$orderby=Id&$top=30&$skiptoken='forge'' with following message : An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServerWarningLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.StsAuthenticationHandler.<SendAsync>d__9.MoveNext()

Below is the Ansible playbook logic, which was working fine from past couple of years, but that also return same error. 
 - name: Install AWS CLI
    win_chocolatey:
      name: awscli
      state: present

Does anybody aware of this error ?
```

**Comment by pauby** [comment]
> awscli
By installing, you accept licenses for the packages.
awscli not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,

The error is being shown as [the `aws-cli` package does not exist on the Chocolatey Community Repository](https://community.chocolatey.org/packages/aws-cli).
