### ISSUE TITLE
A pin is not created for existing installations (prior to new choco)

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#60]
This looks due in part to the folder not package information folder not being created.

```
C:\codelocal\chocolatey2\code_drop\nuget [master +0 ~1 -0]> choco pin add -n ruby -version 1.9.3.54500 -d
Chocolatey v0.9.9.0
Chocolatey is running on Windows v 6.1.7601.65536
Command line: "C:\ProgramData\Chocolatey\choco.exe" pin add -n ruby -version 1.9.3.54500 -d
Received arguments: pin add -n ruby -version 1.9.3.54500 -d
Configuration: CommandName='pin'|ContainsLegacyPackageInstalls='True'|CommandExecutionTimeoutSeconds='2700'|Sources='C:\ProgramData\Chocolatey\lib'|Debug='True'|Verbose='False'|Force='False'|Noop='False'|HelpRequested='False'|RegularOuptut='True'|PromptForConfirmation='False'|AcceptLicense='False'|AllowUnofficialBuild='False'|Input='add'|Version='1.9.3.54500'|AllVersions='True'|SkipPackageInstallProvider='False'|Prerelease='True'|ForceX86='False'|OverrideArguments='False'|NotSilent='False'|IgnoreDependencies='False'|AllowMultipleVersions='False'|ForceDependencies='False'|Information.PlatformType='Windows'|Information.PlatformVersion='6.1.7601.65536'|Information.ChocolateyVersion='0.9.9.0'|Information.ChocolateyProductVersion='0.9.9-27319d4e'|Information.FullName='choco, Version=0.9.9.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|Information.Is64Bit='True'|Information.IsInteractive='True'|Features.AutoUninstaller='False'|Features.CheckSumFiles='True'|ListCommand.LocalOnly='True'|ListCommand.IncludeRegistryPrograms='False'|NewCommand.AutomaticPackage='False'|SourceCommand.Command='unknown'|FeatureCommand.Command='unknown'|PushCommand.TimeoutInSeconds='0'|PinCommand.Name='ruby'|PinCommand.Command='add'|
_ Chocolatey:ChocolateyPinCommand - Normal Run Mode _
Chocolatey had an error occur:
System.ApplicationException: Unable to find package named 'ruby' (version '1.9.3.54500') to pin. Please check to ensure it is installed.
   at chocolatey.infrastructure.app.commands.ChocolateyPinCommand.set_pin(IPackageManager packageManager, ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
Exiting with 1
```

**Comment by ferventcoder** [comment]
It's not exactly what is happening, some things find the pin just fine.

**Comment by ferventcoder** [comment]
It fails because it doesn't actually find the package itself, so it can't create the package information folder.
