### ISSUE TITLE
Handle null items better

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#853]
There are some errors like

~~~sh
[ERROR] - Value cannot be null.
Parameter name: path
~~~

 That tend to crop up when things do not install correctly. Handle these better.

**Comment by caleyg** [comment]
Greetings-

I'm seeing something similar while trying to do  `choco install .\selenium-standalone-server --noop --debug --verbose`

```
PS C:\choco-utils> choco install .\selenium-standalone-server --noop --debug --verbose
Chocolatey is running on Windows v 6.2.9200.0
Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
Command line: "C:\ProgramData\chocolatey\choco.exe" install .\selenium-standalone-server --noop --debug --verbose
Received arguments: install .\selenium-standalone-server --noop --debug --verbose
RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
Sending message 'PreRunMessage' out if there are subscribers...
[Pending] Removing all pending packages that should not be considered installed...
The source '' evaluated to a 'normal' source type

NOTE: Hiding sensitive configuration data! Please double and triple 
 check to be sure no sensitive data is shown, especially if copying 
 output to a gist for review.
Configuration: CommandName='install'|
CacheLocation='C:\Users\Administrator\AppData\Local\Temp\2\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
SourceType='normal'|Debug='True'|Verbose='True'|Force='False'|
Noop='True'|HelpRequested='False'|RegularOutput='True'|
QuietOutput='False'|PromptForConfirmation='True'|AcceptLicense='False'|
AllowUnofficialBuild='False'|Input='.\selenium-standalone-server'|
AllVersions='False'|SkipPackageInstallProvider='False'|
PackageNames='.\selenium-standalone-server'|Prerelease='False'|
ForceX86='False'|OverrideArguments='False'|NotSilent='False'|
IgnoreDependencies='False'|AllowMultipleVersions='False'|
AllowDowngrade='False'|ForceDependencies='False'|
Information.PlatformType='Windows'|
Information.PlatformVersion='6.2.9200.0'|
Information.PlatformName='Windows Server 2012'|
Information.ChocolateyVersion='0.9.10.2'|
Information.ChocolateyProductVersion='0.9.10.2'|
Information.FullName='choco, Version=0.9.10.2, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|`
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Features.AutoUninstaller='True'|
Features.CheckSumFiles='True'|Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
_ Chocolatey:ChocolateyInstallCommand - Noop Mode _
Chocolatey would have used NuGet to install packages (if they are not already installed):
.\selenium-standalone-server
Attempting to create directory "C:\Users\Administrator\AppData\Local\Temp\2\Chocolatey\TempInstalls_20160709_173543_56
42".
Chocolatey had an error occur:
System.NullReferenceException: Object reference not set to an instance of an object.
   at chocolatey.infrastructure.app.nuget.NugetCommon.GetRemoteRepository(ChocolateyConfiguration configuration, ILogg
er nugetLogger)
   at chocolatey.infrastructure.app.nuget.NugetCommon.GetPackageManager(ChocolateyConfiguration configuration, ILogger
 nugetLogger, Action`1 installSuccessAction, Action`1 uninstallSuccessAction, Boolean addUninstallHandler)
   at chocolatey.infrastructure.app.services.NugetService.install_run(ChocolateyConfiguration config, Action`1 continu
eAction)
   at chocolatey.infrastructure.app.services.NugetService.install_noop(ChocolateyConfiguration config, Action`1 contin
ueAction)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runner_action(ChocolateyConfigura
tion config, Action`1 action)
   at chocolatey.infrastructure.app.services.ChocolateyPackageService.install_noop(ChocolateyConfiguration config)
   at chocolatey.infrastructure.app.runners.GenericRunner.find_command(ChocolateyConfiguration config, Container conta
iner, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boo
lean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Cont
ainer container)
   at chocolatey.console.Program.Main(String[] args)
Exiting with 1

**Comment by caleyg** [comment]
so I was doing `choco install .\selenium-standalone-server --noop --debug —verbose` instead of `choco install .\selenium-standalone-server.2.53.1.nupkg --noop --debug —verbose`

It executed fine now. `.\selenium-standalone-server ` was the unpacked nupkg
