### ISSUE TITLE
Intermittent Access Denied errors when trying clear/delete app folder contents during choco upgrade.

### ISSUE THREAD

**Issue by OpusX** [chocolatey/choco#936]
### What You Are Seeing?

Got this error when testing chocolatey usage for first time.  Using simple package with some custom scripts, test text files and a simple service that locks a file in app folder.

I am getting intermittent Access Denied errors when running choco upgrade.  Sometimes the errors occur during chocolateyBeforeModify.ps1 when trying to delete directory and contents of C:\ProgramData\chocolatey\lib\myApp and sometimes after the execution of chocolateyBeforeModify.ps1 and before chocolateyInstall.ps1.  The errors in between script executions relate to Access denied moving contents of C:\ProgramData\chocolatey\lib\myApp  to C:\ProgramData\chocolatey\lib-bkp or C:\ProgramData\chocolatey\lib-bad. Approximately 50% of the time I get no errors and upgrade is successful.  And approximately 50% of the time I get a number of Access Denied errors, either at the end of the chocolateyBeforeModify.ps1 and/or after chocolateyBeforeModify.ps1 and before chocolateyInstall.ps1.  No changes to package are made between times it fails and times it succeeds.

Just a note, the service that locks the file is stopped and deleted before the end of the chocolateyBeforeModify.ps1 script completes.  So this would not be the issue.  Also the file that it locks is always successfully deleted in a previous step.

NOTE: When testing with Powershell 3.0 one of the Engineers here did not see this behavior and could not reproduce.  Once he upgraded to Powershell 4.0 he began seeing the same Access Denied errors in the same inconsistent manner that I was experiencing during my testing.
### What is Expected?

The previously installed app directory should be cleaned up and deleted prior to the upgrade during execution of the chocolateyBeforeModify.ps1, then the chocolateyInstall.ps1 can deploy new version.

This should work in Powershell 4.0
### How Did You Get This To Happen? (Steps to Reproduce)

On a Windows 2012 R2 using Powershell 4.0:

1) Install new application "myApp"
2) create an upgrade (in this test it was just the addition of a single text file)
3) run upgrade

chocolateyBeforeModify steps
1) Test to see if service exists
2) If service exists stop and remove it
3) Test to see if symlinks exist
4) If symlinks exist remove contents of target and delete symlink
5) Test to see if app directory exists.
6) If directory exists delete any content as well as directory

When the error does occur it always occurs on step 6 or after chocolateyBeforeModify.ps1 and before chocolateyInstall.ps1 while trying to push new package to C:\ProgramData\chocolatey\lib
### Output Log

GIST LINK - https://gist.github.com/anonymous/98e070994cdda7195fdab59761186ef8
### Log section with error

2016-08-31 11:14:08,403 [INFO ] - Removing Directory...
2016-08-31 11:14:08,403 [WARN ] - WARNING: Failed to delete C:\ProgramData\chocolatey\lib\myApp
2016-08-31 11:14:08,465 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\myApp\tools\chocolateybeforemodify.ps1' -installArguments '' -packageParameters '''] exited with '1'.
2016-08-31 11:14:08,465 [DEBUG] - Backing up existing myApp prior to upgrade.
2016-08-31 11:14:08,481 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\myApp'
 to 'C:\ProgramData\chocolatey\lib-bkp\myApp'
2016-08-31 11:14:08,481 [WARN ] - This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 System.IO.IOException: Access to the path 'C:\ProgramData\chocolatey\lib\myApp' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2016-08-31 11:14:08,794 [WARN ] - This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 System.IO.IOException: Access to the path 'C:\ProgramData\chocolatey\lib\myApp' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2016-08-31 11:14:09,200 [ERROR] - Maximum tries of 3 reached. Throwing error.
2016-08-31 11:14:09,200 [WARN ] - Move failed with message:
 Access to the path 'C:\ProgramData\chocolatey\lib\myApp' is denied.
 Attempting backup move method.
2016-08-31 11:14:09,200 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib-bkp\myApp".
2016-08-31 11:14:09,200 [ERROR] - Error during backup (move phase):
 Access to the path 'C:\ProgramData\chocolatey\lib\myApp\content' is denied.
2016-08-31 11:14:10,715 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\myApp'
2016-08-31 11:14:10,715 [ERROR] - myApp not upgraded. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\myApp\content' is denied.
2016-08-31 11:14:10,731 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey.chocolatey\myApp.1.0.1.files.update".
2016-08-31 11:14:10,731 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey.chocolatey\myApp.1.0.1.arguments".
2016-08-31 11:14:10,731 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey.chocolatey\myApp.1.0.1.sxs".
2016-08-31 11:14:10,731 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey.chocolatey\myApp.1.0.1.pin".
2016-08-31 11:14:10,747 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2016-08-31 11:14:10,747 [ERROR] - The upgrade of myapp was NOT successful.
2016-08-31 11:14:10,747 [ERROR] - myApp not upgraded. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\myApp\content' is denied.
2016-08-31 11:14:10,747 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\myApp'
 to 'C:\ProgramData\chocolatey\lib-bad\myApp'
2016-08-31 11:14:10,747 [WARN ] - This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 System.IO.IOException: Access to the path 'C:\ProgramData\chocolatey\lib\myApp' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2016-08-31 11:14:11,059 [WARN ] - This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 System.IO.IOException: Access to the path 'C:\ProgramData\chocolatey\lib\myApp' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2016-08-31 11:14:11,465 [ERROR] - Maximum tries of 3 reached. Throwing error.
2016-08-31 11:14:11,465 [WARN ] - Move failed with message:
 Access to the path 'C:\ProgramData\chocolatey\lib\myApp' is denied.
 Attempting backup move method.
2016-08-31 11:14:11,465 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib-bad\myApp".
2016-08-31 11:14:11,465 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\myApp.chocolateyPending'
 to 'C:\ProgramData\chocolatey\lib-bad\myApp.chocolateyPending'
2016-08-31 11:14:11,465 [ERROR] - Could not move bad package to failure directory It will show as installed.
 C:\ProgramData\chocolatey\lib\myApp
 The error:
 System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib\myApp\content' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.move_directory(String directoryPath, String newDirectoryPath)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass4.<try_catch_with_logging_exception>b__3()
   at chocolatey.infrastructure.tolerance.FaultTolerance.try_catch_with_logging_exception[T](Func`1 function, String errorMessage, Boolean throwError, Boolean logWarningInsteadOfError, Boolean logDebugInsteadOfError, Boolean isSilent)
2016-08-31 11:14:11,465 [DEBUG] - Attempting rollback
2016-08-31 11:14:11,465 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib-bkp\myApp'
 to 'C:\ProgramData\chocolatey\lib\myApp'
2016-08-31 11:14:11,465 [WARN ] - This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2016-08-31 11:14:11,794 [WARN ] - This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 System.IO.IOException: Cannot create a file when that file already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0()
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurationMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent)
2016-08-31 11:14:12,200 [ERROR] - Maximum tries of 3 reached. Throwing error.
2016-08-31 11:14:12,200 [WARN ] - Move failed with message:
 Cannot create a file when that file already exists.

 Attempting backup move method.
2016-08-31 11:14:13,215 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bkp\myApp".
2016-08-31 11:14:15,231 [WARN ] - 
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2016-08-31 11:14:15,231 [INFO ] - 
2016-08-31 11:14:15,231 [ERROR] - Failures
2016-08-31 11:14:15,231 [ERROR] -  - myapp (exited 1) - myApp not upgraded. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\myApp\content' is denied.
2016-08-31 11:14:15,247 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2016-08-31 11:14:15,247 [DEBUG] - Exiting with 1

**Comment by ferventcoder** [comment]
Hello @OpusX  - let's take a look at the file here

~~~powershell
Param([string] $Service = "Lockfile",
      [string] $DirPath = "C:\ProgramData\chocolatey\lib\myApp",
      [string] $SymPath = "C:\Utils\myApp",
      [string] $SymTarget = "$DirPath\content",
      [string] $DisplayName = "Lockfile",
      [string] $BinaryPathName = "C:\ProgramData\chocolatey\lib\myApp\content\Lockfile.ps1")

$ScriptPath = Split-Path $myInvocation.MyCommand.Path
Import-Module "$ScriptPath\helpers\manage-ntservice"
Import-Module "$ScriptPath\helpers\manage-symlink"

# Test if service exists
$ServiceExist = add-event {test-doesserviceexist -name $Service}
Write-Host "Does Service Exist: $ServiceExist"

# If Service exists
if ($ServiceExist -eq "True")
{
    # stop and remove
    $counter = 0
    Write-Host "Stopping Service..." -NoNewline
    add-event {Set-NtService -name $Service -stop }
    Do{$srvState = (get-service $Service).Status;start-sleep 1;$counter++}until(($srvState -eq "Stopped") -or ($counter -eq 10))
    if ($srvState -ne "Stopped"){Write-Host "not stopped";exit 1}
    Write-Host "Stopped"
    start-sleep 5
    
    Write-Host "Removing Service..." -NoNewline
    add-event {remove-service -name $Service} 
    start-sleep 5
    $SvcExist = get-service $Service -ea SilentlyContinue
    if ($SvcExist -eq $null){write-host "Success"}else{write-host "Failure"}

}

# if symlink exists remove   
$SymLinkExists = add-event {Test-SymLink -path $SymTarget -symname $SymPath}
Write-host "Does Symlink Exist: $SymLinkExists"

    
if ($SymLinkExists -eq "True")
{
    Write-Host "Removing Symlink..." -NoNewline
    add-event {remove-directory $SymPath}
    $SymExist = Test-Path $SymPath
    if ($SymExist -eq $true){write-host "Failure"}else{Write-host "Success"}  
    Start-Sleep 5      

}
    
    
# if directory exists remove
$DirExist = Test-Path $DirPath
if ($DirExist -eq $true)
{
    Write-Host "Removing Directory..." -NoNewline
    add-event {remove-directory $DirPath}
    if (test-path $DirPath){write-host "Failure"}else{Write-host "Success"}
} 
~~~~

**Comment by ferventcoder** [comment]
First I noticed, you are using parameters you are passing, but that is not recommended way of setting up the scripts. Did you run `choco new` to generate your scripts?

Then I notice
`[string] $DirPath = "C:\ProgramData\chocolatey\lib\myApp",`  - You should probably use script root.

Removing the package folder - `$DirPath` (which is a Chocolatey package directory) - don't do it. Chocolatey handles removing the package for you. You can actually cause problems in removing the package folder instead of letting Chocolatey handle this during upgrade/uninstall. 

For the most part, assume Chocolatey does a lot of smart things so you don't have to write heavily involved scripts.

**Comment by ferventcoder** [comment]
BeforeModify is meant to do things that are necessary before upgrade/uninstall only. If you are repeating any of that in your other scripts, you probably should only do it in those other scripts.

**Comment by ferventcoder** [comment]
Closing this due to inactivity - if you want to address this later, feel free to comment and we can reopen this.
